/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen-cached. DO NOT EDIT.

package v1alpha1

// ArtifactInputsApplyConfiguration represents a declarative configuration of the ArtifactInputs type for use
// with apply.
//
// ArtifactInputs is the closed, typed input set accepted by the allowlisted
// collector recipes. It deliberately has no command, path, image, or output
// fields.
type ArtifactInputsApplyConfiguration struct {
	// maxArchiveBytes is the server-selected compressed archive limit.
	MaxArchiveBytes *int64 `json:"maxArchiveBytes,omitempty"`
	// maxAgeMinutes bounds crashdump collection age.
	MaxAgeMinutes *int64 `json:"maxAgeMinutes,omitempty"`
	// detailLevel is the system-summary detail level.
	DetailLevel *string `json:"detailLevel,omitempty"`
}

// ArtifactInputsApplyConfiguration constructs a declarative configuration of the ArtifactInputs type for use with
// apply.
func ArtifactInputs() *ArtifactInputsApplyConfiguration {
	return &ArtifactInputsApplyConfiguration{}
}

// WithMaxArchiveBytes sets the MaxArchiveBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxArchiveBytes field is set to the value of the last call.
func (b *ArtifactInputsApplyConfiguration) WithMaxArchiveBytes(value int64) *ArtifactInputsApplyConfiguration {
	b.MaxArchiveBytes = &value
	return b
}

// WithMaxAgeMinutes sets the MaxAgeMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAgeMinutes field is set to the value of the last call.
func (b *ArtifactInputsApplyConfiguration) WithMaxAgeMinutes(value int64) *ArtifactInputsApplyConfiguration {
	b.MaxAgeMinutes = &value
	return b
}

// WithDetailLevel sets the DetailLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DetailLevel field is set to the value of the last call.
func (b *ArtifactInputsApplyConfiguration) WithDetailLevel(value string) *ArtifactInputsApplyConfiguration {
	b.DetailLevel = &value
	return b
}
