/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ArtifactResourceReferenceApplyConfiguration represents a declarative configuration of the ArtifactResourceReference type for use
// with apply.
//
// ArtifactResourceReference identifies one spoke resource created for this
// artifact. UID and resourceVersion make restart cleanup safe against name
// reuse and replacement; this is intentionally not an owner reference because
// the artifact and resource live in different clusters.
type ArtifactResourceReferenceApplyConfiguration struct {
	// kind is the Kubernetes resource kind.
	Kind *string `json:"kind,omitempty"`
	// namespace is the spoke namespace.
	Namespace *string `json:"namespace,omitempty"`
	// name is the spoke resource name.
	Name *string `json:"name,omitempty"`
	// uid is the exact UID observed after creation.
	UID *string `json:"uid,omitempty"`
	// resourceVersion is the version observed after creation.
	ResourceVersion *string `json:"resourceVersion,omitempty"`
	// operationID is the persisted create intent marker used for recovery.
	OperationID *string `json:"operationID,omitempty"`
}

// ArtifactResourceReferenceApplyConfiguration constructs a declarative configuration of the ArtifactResourceReference type for use with
// apply.
func ArtifactResourceReference() *ArtifactResourceReferenceApplyConfiguration {
	return &ArtifactResourceReferenceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ArtifactResourceReferenceApplyConfiguration) WithKind(value string) *ArtifactResourceReferenceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ArtifactResourceReferenceApplyConfiguration) WithNamespace(value string) *ArtifactResourceReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ArtifactResourceReferenceApplyConfiguration) WithName(value string) *ArtifactResourceReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ArtifactResourceReferenceApplyConfiguration) WithUID(value string) *ArtifactResourceReferenceApplyConfiguration {
	b.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ArtifactResourceReferenceApplyConfiguration) WithResourceVersion(value string) *ArtifactResourceReferenceApplyConfiguration {
	b.ResourceVersion = &value
	return b
}

// WithOperationID sets the OperationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperationID field is set to the value of the last call.
func (b *ArtifactResourceReferenceApplyConfiguration) WithOperationID(value string) *ArtifactResourceReferenceApplyConfiguration {
	b.OperationID = &value
	return b
}
