/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ArtifactOutboxStatusApplyConfiguration represents a declarative configuration of the ArtifactOutboxStatus type for use
// with apply.
//
// ArtifactOutboxStatus records bounded retry and lease evidence without
// exposing provider details.
type ArtifactOutboxStatusApplyConfiguration struct {
	// kind is the current durable provider operation.
	Kind *apiv1alpha1.ArtifactOperationKind `json:"kind,omitempty"`
	// attempt is bounded by the controller's retry policy.
	Attempt *int32 `json:"attempt,omitempty"`
	// leaseOwner identifies the controller worker holding the operation lease.
	LeaseOwner *string `json:"leaseOwner,omitempty"`
	// leaseExpiresAt bounds abandoned work recovery.
	LeaseExpiresAt *v1.Time `json:"leaseExpiresAt,omitempty"`
	// lastError is a bounded redacted classification, never a provider URL or credential.
	LastError *string `json:"lastError,omitempty"`
}

// ArtifactOutboxStatusApplyConfiguration constructs a declarative configuration of the ArtifactOutboxStatus type for use with
// apply.
func ArtifactOutboxStatus() *ArtifactOutboxStatusApplyConfiguration {
	return &ArtifactOutboxStatusApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ArtifactOutboxStatusApplyConfiguration) WithKind(value apiv1alpha1.ArtifactOperationKind) *ArtifactOutboxStatusApplyConfiguration {
	b.Kind = &value
	return b
}

// WithAttempt sets the Attempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Attempt field is set to the value of the last call.
func (b *ArtifactOutboxStatusApplyConfiguration) WithAttempt(value int32) *ArtifactOutboxStatusApplyConfiguration {
	b.Attempt = &value
	return b
}

// WithLeaseOwner sets the LeaseOwner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaseOwner field is set to the value of the last call.
func (b *ArtifactOutboxStatusApplyConfiguration) WithLeaseOwner(value string) *ArtifactOutboxStatusApplyConfiguration {
	b.LeaseOwner = &value
	return b
}

// WithLeaseExpiresAt sets the LeaseExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeaseExpiresAt field is set to the value of the last call.
func (b *ArtifactOutboxStatusApplyConfiguration) WithLeaseExpiresAt(value v1.Time) *ArtifactOutboxStatusApplyConfiguration {
	b.LeaseExpiresAt = &value
	return b
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *ArtifactOutboxStatusApplyConfiguration) WithLastError(value string) *ArtifactOutboxStatusApplyConfiguration {
	b.LastError = &value
	return b
}
