/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AuditQueueConfigApplyConfiguration represents a declarative configuration of the AuditQueueConfig type for use
// with apply.
//
// AuditQueueConfig configures the async event queue.
type AuditQueueConfigApplyConfiguration struct {
	// Size is the queue capacity.
	// Larger queues handle traffic spikes better but use more memory.
	Size *int `json:"size,omitempty"`
	// Workers is the number of concurrent sink writers.
	Workers *int `json:"workers,omitempty"`
	// DropOnFull drops events when the queue is full.
	// If false, enqueue blocks up to the caller deadline or five seconds.
	DropOnFull *bool `json:"dropOnFull,omitempty"`
	// RetryAttempts bounds attempts for a failed sink write, including the first.
	RetryAttempts *int `json:"retryAttempts,omitempty"`
	// RetryInitialBackoffMillis is the initial exponential retry delay.
	RetryInitialBackoffMillis *int `json:"retryInitialBackoffMillis,omitempty"`
	// RetryMaxBackoffMillis caps the exponential retry delay.
	RetryMaxBackoffMillis *int `json:"retryMaxBackoffMillis,omitempty"`
	// RetryTimeoutSeconds bounds the complete delivery attempt, including backoff.
	// Failed batches remain in the worker until delivered or this bound is reached.
	RetryTimeoutSeconds *int `json:"retryTimeoutSeconds,omitempty"`
}

// AuditQueueConfigApplyConfiguration constructs a declarative configuration of the AuditQueueConfig type for use with
// apply.
func AuditQueueConfig() *AuditQueueConfigApplyConfiguration {
	return &AuditQueueConfigApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithSize(value int) *AuditQueueConfigApplyConfiguration {
	b.Size = &value
	return b
}

// WithWorkers sets the Workers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workers field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithWorkers(value int) *AuditQueueConfigApplyConfiguration {
	b.Workers = &value
	return b
}

// WithDropOnFull sets the DropOnFull field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DropOnFull field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithDropOnFull(value bool) *AuditQueueConfigApplyConfiguration {
	b.DropOnFull = &value
	return b
}

// WithRetryAttempts sets the RetryAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryAttempts field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithRetryAttempts(value int) *AuditQueueConfigApplyConfiguration {
	b.RetryAttempts = &value
	return b
}

// WithRetryInitialBackoffMillis sets the RetryInitialBackoffMillis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryInitialBackoffMillis field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithRetryInitialBackoffMillis(value int) *AuditQueueConfigApplyConfiguration {
	b.RetryInitialBackoffMillis = &value
	return b
}

// WithRetryMaxBackoffMillis sets the RetryMaxBackoffMillis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryMaxBackoffMillis field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithRetryMaxBackoffMillis(value int) *AuditQueueConfigApplyConfiguration {
	b.RetryMaxBackoffMillis = &value
	return b
}

// WithRetryTimeoutSeconds sets the RetryTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryTimeoutSeconds field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithRetryTimeoutSeconds(value int) *AuditQueueConfigApplyConfiguration {
	b.RetryTimeoutSeconds = &value
	return b
}
