/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AuditDestinationApplyConfiguration represents a declarative configuration of the AuditDestination type for use
// with apply.
//
// AuditDestination specifies where audit events are sent.
type AuditDestinationApplyConfiguration struct {
	// type specifies the destination type.
	Type *string `json:"type,omitempty"`
	// url is the webhook URL (required for webhook type).
	URL *string `json:"url,omitempty"`
	// headers are additional headers for webhook requests.
	Headers map[string]string `json:"headers,omitempty"`
}

// AuditDestinationApplyConfiguration constructs a declarative configuration of the AuditDestination type for use with
// apply.
func AuditDestination() *AuditDestinationApplyConfiguration {
	return &AuditDestinationApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AuditDestinationApplyConfiguration) WithType(value string) *AuditDestinationApplyConfiguration {
	b.Type = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *AuditDestinationApplyConfiguration) WithURL(value string) *AuditDestinationApplyConfiguration {
	b.URL = &value
	return b
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *AuditDestinationApplyConfiguration) WithHeaders(entries map[string]string) *AuditDestinationApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}
