/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AuditQueueConfigApplyConfiguration represents a declarative configuration of the AuditQueueConfig type for use
// with apply.
//
// AuditQueueConfig configures the async event queue.
type AuditQueueConfigApplyConfiguration struct {
	// Size is the queue capacity.
	// Larger queues handle traffic spikes better but use more memory.
	Size *int `json:"size,omitempty"`
	// Workers is the number of concurrent sink writers.
	Workers *int `json:"workers,omitempty"`
	// DropOnFull silently drops events when queue is full.
	// If false, a warning is logged for each dropped event.
	DropOnFull *bool `json:"dropOnFull,omitempty"`
}

// AuditQueueConfigApplyConfiguration constructs a declarative configuration of the AuditQueueConfig type for use with
// apply.
func AuditQueueConfig() *AuditQueueConfigApplyConfiguration {
	return &AuditQueueConfigApplyConfiguration{}
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithSize(value int) *AuditQueueConfigApplyConfiguration {
	b.Size = &value
	return b
}

// WithWorkers sets the Workers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workers field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithWorkers(value int) *AuditQueueConfigApplyConfiguration {
	b.Workers = &value
	return b
}

// WithDropOnFull sets the DropOnFull field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DropOnFull field is set to the value of the last call.
func (b *AuditQueueConfigApplyConfiguration) WithDropOnFull(value bool) *AuditQueueConfigApplyConfiguration {
	b.DropOnFull = &value
	return b
}
