/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AuditFilterConfigApplyConfiguration represents a declarative configuration of the AuditFilterConfig type for use
// with apply.
//
// AuditFilterConfig controls which events are captured.
type AuditFilterConfigApplyConfiguration struct {
	// IncludeEventTypes explicitly includes these event types.
	// Empty means include all.
	IncludeEventTypes []string `json:"includeEventTypes,omitempty"`
	// ExcludeEventTypes excludes these event types.
	// Takes precedence over IncludeEventTypes.
	ExcludeEventTypes []string `json:"excludeEventTypes,omitempty"`
	// IncludeUsers only captures events from these users.
	// Supports glob patterns (e.g., "system:*").
	IncludeUsers []string `json:"includeUsers,omitempty"`
	// ExcludeUsers excludes events from these users.
	// Useful for filtering out service accounts.
	ExcludeUsers []string `json:"excludeUsers,omitempty"`
	// IncludeNamespaces only captures events in these namespaces.
	// Supports pattern matching (glob-style) and label-based namespace selection.
	IncludeNamespaces *NamespaceFilterApplyConfiguration `json:"includeNamespaces,omitempty"`
	// ExcludeNamespaces excludes events from these namespaces.
	// Useful for filtering out kube-system.
	// Supports pattern matching (glob-style) and label-based namespace selection.
	ExcludeNamespaces *NamespaceFilterApplyConfiguration `json:"excludeNamespaces,omitempty"`
	// IncludeResources only captures events for these resource kinds.
	IncludeResources []string `json:"includeResources,omitempty"`
	// ExcludeResources excludes events for these resource kinds.
	ExcludeResources []string `json:"excludeResources,omitempty"`
}

// AuditFilterConfigApplyConfiguration constructs a declarative configuration of the AuditFilterConfig type for use with
// apply.
func AuditFilterConfig() *AuditFilterConfigApplyConfiguration {
	return &AuditFilterConfigApplyConfiguration{}
}

// WithIncludeEventTypes adds the given value to the IncludeEventTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IncludeEventTypes field.
func (b *AuditFilterConfigApplyConfiguration) WithIncludeEventTypes(values ...string) *AuditFilterConfigApplyConfiguration {
	for i := range values {
		b.IncludeEventTypes = append(b.IncludeEventTypes, values[i])
	}
	return b
}

// WithExcludeEventTypes adds the given value to the ExcludeEventTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludeEventTypes field.
func (b *AuditFilterConfigApplyConfiguration) WithExcludeEventTypes(values ...string) *AuditFilterConfigApplyConfiguration {
	for i := range values {
		b.ExcludeEventTypes = append(b.ExcludeEventTypes, values[i])
	}
	return b
}

// WithIncludeUsers adds the given value to the IncludeUsers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IncludeUsers field.
func (b *AuditFilterConfigApplyConfiguration) WithIncludeUsers(values ...string) *AuditFilterConfigApplyConfiguration {
	for i := range values {
		b.IncludeUsers = append(b.IncludeUsers, values[i])
	}
	return b
}

// WithExcludeUsers adds the given value to the ExcludeUsers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludeUsers field.
func (b *AuditFilterConfigApplyConfiguration) WithExcludeUsers(values ...string) *AuditFilterConfigApplyConfiguration {
	for i := range values {
		b.ExcludeUsers = append(b.ExcludeUsers, values[i])
	}
	return b
}

// WithIncludeNamespaces sets the IncludeNamespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IncludeNamespaces field is set to the value of the last call.
func (b *AuditFilterConfigApplyConfiguration) WithIncludeNamespaces(value *NamespaceFilterApplyConfiguration) *AuditFilterConfigApplyConfiguration {
	b.IncludeNamespaces = value
	return b
}

// WithExcludeNamespaces sets the ExcludeNamespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExcludeNamespaces field is set to the value of the last call.
func (b *AuditFilterConfigApplyConfiguration) WithExcludeNamespaces(value *NamespaceFilterApplyConfiguration) *AuditFilterConfigApplyConfiguration {
	b.ExcludeNamespaces = value
	return b
}

// WithIncludeResources adds the given value to the IncludeResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IncludeResources field.
func (b *AuditFilterConfigApplyConfiguration) WithIncludeResources(values ...string) *AuditFilterConfigApplyConfiguration {
	for i := range values {
		b.IncludeResources = append(b.IncludeResources, values[i])
	}
	return b
}

// WithExcludeResources adds the given value to the ExcludeResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludeResources field.
func (b *AuditFilterConfigApplyConfiguration) WithExcludeResources(values ...string) *AuditFilterConfigApplyConfiguration {
	for i := range values {
		b.ExcludeResources = append(b.ExcludeResources, values[i])
	}
	return b
}
