/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	breakglassv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
)

// AuditSinkConfigApplyConfiguration represents a declarative configuration of the AuditSinkConfig type for use
// with apply.
//
// AuditSinkConfig defines a single audit sink destination.
type AuditSinkConfigApplyConfiguration struct {
	// Name is a unique identifier for this sink.
	Name *string `json:"name,omitempty"`
	// Type is the sink type.
	Type *breakglassv1alpha1.AuditSinkType `json:"type,omitempty"`
	// Kafka configuration (required when type=kafka).
	Kafka *KafkaSinkSpecApplyConfiguration `json:"kafka,omitempty"`
	// Webhook configuration (required when type=webhook).
	Webhook *WebhookSinkSpecApplyConfiguration `json:"webhook,omitempty"`
	// Log configuration (optional when type=log).
	Log *LogSinkSpecApplyConfiguration `json:"log,omitempty"`
	// Kubernetes configuration (optional when type=kubernetes).
	Kubernetes *KubernetesSinkSpecApplyConfiguration `json:"kubernetes,omitempty"`
	// EventTypes limits this sink to specific event types.
	// Empty means all events.
	EventTypes []string `json:"eventTypes,omitempty"`
	// MinSeverity sets the minimum severity level for this sink.
	// Events below this severity are not sent to this sink.
	MinSeverity *string `json:"minSeverity,omitempty"`
}

// AuditSinkConfigApplyConfiguration constructs a declarative configuration of the AuditSinkConfig type for use with
// apply.
func AuditSinkConfig() *AuditSinkConfigApplyConfiguration {
	return &AuditSinkConfigApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithName(value string) *AuditSinkConfigApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithType(value breakglassv1alpha1.AuditSinkType) *AuditSinkConfigApplyConfiguration {
	b.Type = &value
	return b
}

// WithKafka sets the Kafka field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kafka field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithKafka(value *KafkaSinkSpecApplyConfiguration) *AuditSinkConfigApplyConfiguration {
	b.Kafka = value
	return b
}

// WithWebhook sets the Webhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Webhook field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithWebhook(value *WebhookSinkSpecApplyConfiguration) *AuditSinkConfigApplyConfiguration {
	b.Webhook = value
	return b
}

// WithLog sets the Log field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Log field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithLog(value *LogSinkSpecApplyConfiguration) *AuditSinkConfigApplyConfiguration {
	b.Log = value
	return b
}

// WithKubernetes sets the Kubernetes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kubernetes field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithKubernetes(value *KubernetesSinkSpecApplyConfiguration) *AuditSinkConfigApplyConfiguration {
	b.Kubernetes = value
	return b
}

// WithEventTypes adds the given value to the EventTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EventTypes field.
func (b *AuditSinkConfigApplyConfiguration) WithEventTypes(values ...string) *AuditSinkConfigApplyConfiguration {
	for i := range values {
		b.EventTypes = append(b.EventTypes, values[i])
	}
	return b
}

// WithMinSeverity sets the MinSeverity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinSeverity field is set to the value of the last call.
func (b *AuditSinkConfigApplyConfiguration) WithMinSeverity(value string) *AuditSinkConfigApplyConfiguration {
	b.MinSeverity = &value
	return b
}
