/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AuditSinkStatusApplyConfiguration represents a declarative configuration of the AuditSinkStatus type for use
// with apply.
//
// AuditSinkStatus contains status for a single sink.
type AuditSinkStatusApplyConfiguration struct {
	// Name of the sink.
	Name *string `json:"name,omitempty"`
	// Ready indicates if the sink is operational.
	Ready *bool `json:"ready,omitempty"`
	// LastError is the most recent error, if any.
	LastError *string `json:"lastError,omitempty"`
	// LastSuccessTime is when the sink last successfully processed an event.
	LastSuccessTime *v1.Time `json:"lastSuccessTime,omitempty"`
	// EventsWritten is the number of events written to this sink.
	EventsWritten *int64 `json:"eventsWritten,omitempty"`
}

// AuditSinkStatusApplyConfiguration constructs a declarative configuration of the AuditSinkStatus type for use with
// apply.
func AuditSinkStatus() *AuditSinkStatusApplyConfiguration {
	return &AuditSinkStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AuditSinkStatusApplyConfiguration) WithName(value string) *AuditSinkStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *AuditSinkStatusApplyConfiguration) WithReady(value bool) *AuditSinkStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithLastError sets the LastError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastError field is set to the value of the last call.
func (b *AuditSinkStatusApplyConfiguration) WithLastError(value string) *AuditSinkStatusApplyConfiguration {
	b.LastError = &value
	return b
}

// WithLastSuccessTime sets the LastSuccessTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessTime field is set to the value of the last call.
func (b *AuditSinkStatusApplyConfiguration) WithLastSuccessTime(value v1.Time) *AuditSinkStatusApplyConfiguration {
	b.LastSuccessTime = &value
	return b
}

// WithEventsWritten sets the EventsWritten field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventsWritten field is set to the value of the last call.
func (b *AuditSinkStatusApplyConfiguration) WithEventsWritten(value int64) *AuditSinkStatusApplyConfiguration {
	b.EventsWritten = &value
	return b
}
