/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AutoApproveConfigApplyConfiguration represents a declarative configuration of the AutoApproveConfig type for use
// with apply.
//
// AutoApproveConfig specifies conditions for automatic approval.
type AutoApproveConfigApplyConfiguration struct {
	// groups specifies groups for which sessions are auto-approved.
	Groups []string `json:"groups,omitempty"`
	// clusters specifies clusters where sessions are auto-approved.
	// Supports glob patterns.
	Clusters []string `json:"clusters,omitempty"`
}

// AutoApproveConfigApplyConfiguration constructs a declarative configuration of the AutoApproveConfig type for use with
// apply.
func AutoApproveConfig() *AutoApproveConfigApplyConfiguration {
	return &AutoApproveConfigApplyConfiguration{}
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *AutoApproveConfigApplyConfiguration) WithGroups(values ...string) *AutoApproveConfigApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *AutoApproveConfigApplyConfiguration) WithClusters(values ...string) *AutoApproveConfigApplyConfiguration {
	for i := range values {
		b.Clusters = append(b.Clusters, values[i])
	}
	return b
}
