/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BindingReferenceApplyConfiguration represents a declarative configuration of the BindingReference type for use
// with apply.
//
// BindingReference references a DebugSessionClusterBinding.
type BindingReferenceApplyConfiguration struct {
	// name is the name of the DebugSessionClusterBinding.
	Name *string `json:"name,omitempty"`
	// namespace is the namespace of the DebugSessionClusterBinding.
	Namespace *string `json:"namespace,omitempty"`
}

// BindingReferenceApplyConfiguration constructs a declarative configuration of the BindingReference type for use with
// apply.
func BindingReference() *BindingReferenceApplyConfiguration {
	return &BindingReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BindingReferenceApplyConfiguration) WithName(value string) *BindingReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *BindingReferenceApplyConfiguration) WithNamespace(value string) *BindingReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}
