/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	breakglassv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BreakglassSessionStatusApplyConfiguration represents a declarative configuration of the BreakglassSessionStatus type for use
// with apply.
//
// BreakglassSessionStatus defines the observed state of BreakglassSessionStatus.
type BreakglassSessionStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation of the most recently observed BreakglassSession.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// conditions is an array of current observed BreakglassSession conditions.
	// Tracks conditions like Idle, Approved, Rejected, Expired, Canceled, Active, and SessionExpired
	// Active condition: Set to True when session is approved and within validity window, False otherwise
	// SessionExpired condition: Set to True when session validity period has ended, False while active
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// approvedAt is the time when the session was approved.
	ApprovedAt *metav1.Time `json:"approvedAt,omitempty"`
	// actualStartTime records when the session actually became active.
	// For immediate sessions (no scheduledStartTime): equals ApprovedAt.
	// For scheduled sessions: set when ScheduledStartTime is reached and session transitions to Approved.
	ActualStartTime *metav1.Time `json:"actualStartTime,omitempty"`
	// rejectedAt is the time when the session was rejected by an approver.
	// Only set for SessionStateRejected.
	RejectedAt *metav1.Time `json:"rejectedAt,omitempty"`
	// withdrawnAt is the time when the session was withdrawn by the user.
	// Only set for SessionStateWithdrawn.
	WithdrawnAt *metav1.Time `json:"withdrawnAt,omitempty"`
	// ExpiresAt is the time when the session will expire.
	// This value is set based on spec.MaxValidFor when the session is approved.
	ExpiresAt *metav1.Time `json:"expiresAt,omitempty"`
	// TimeoutAt is the time when the session approval times out if not approved.
	// This value is set when the session is created and only applies while pending approval.
	TimeoutAt *metav1.Time `json:"timeoutAt,omitempty"`
	// retainedUntil is the time when the session object will be removed from the cluster.
	// This value is set based on spec.retainFor when the session is approved.
	RetainedUntil *metav1.Time `json:"retainedUntil,omitempty"`
	// State represents the current state of the Breakglass session.
	State *breakglassv1alpha1.BreakglassSessionState `json:"state,omitempty"`
	// approver is the identity (email) of the last approver who changed the session state.
	Approver *string `json:"approver,omitempty"`
	// approvers is a list of identities (emails) who have approved this session.
	// This is useful when multiple approvers are involved.
	Approvers []string `json:"approvers,omitempty"`
	// approvalReason stores the free-text reason supplied by the approver when approving/rejecting the session.
	ApprovalReason *string `json:"approvalReason,omitempty"`
	// reasonEnded stores a short reason for why the session ended or entered a terminal state.
	// Possible values: "timeExpired", "canceled", "dropped", "withdrawn", "rejected", "duplicateCleanup", "idleTimeout"
	ReasonEnded *string `json:"reasonEnded,omitempty"`
}

// BreakglassSessionStatusApplyConfiguration constructs a declarative configuration of the BreakglassSessionStatus type for use with
// apply.
func BreakglassSessionStatus() *BreakglassSessionStatusApplyConfiguration {
	return &BreakglassSessionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithObservedGeneration(value int64) *BreakglassSessionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BreakglassSessionStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BreakglassSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithApprovedAt sets the ApprovedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovedAt field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithApprovedAt(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.ApprovedAt = &value
	return b
}

// WithActualStartTime sets the ActualStartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActualStartTime field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithActualStartTime(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.ActualStartTime = &value
	return b
}

// WithRejectedAt sets the RejectedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RejectedAt field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithRejectedAt(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.RejectedAt = &value
	return b
}

// WithWithdrawnAt sets the WithdrawnAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WithdrawnAt field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithWithdrawnAt(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.WithdrawnAt = &value
	return b
}

// WithExpiresAt sets the ExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiresAt field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithExpiresAt(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.ExpiresAt = &value
	return b
}

// WithTimeoutAt sets the TimeoutAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutAt field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithTimeoutAt(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.TimeoutAt = &value
	return b
}

// WithRetainedUntil sets the RetainedUntil field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetainedUntil field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithRetainedUntil(value metav1.Time) *BreakglassSessionStatusApplyConfiguration {
	b.RetainedUntil = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithState(value breakglassv1alpha1.BreakglassSessionState) *BreakglassSessionStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithApprover sets the Approver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Approver field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithApprover(value string) *BreakglassSessionStatusApplyConfiguration {
	b.Approver = &value
	return b
}

// WithApprovers adds the given value to the Approvers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Approvers field.
func (b *BreakglassSessionStatusApplyConfiguration) WithApprovers(values ...string) *BreakglassSessionStatusApplyConfiguration {
	for i := range values {
		b.Approvers = append(b.Approvers, values[i])
	}
	return b
}

// WithApprovalReason sets the ApprovalReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovalReason field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithApprovalReason(value string) *BreakglassSessionStatusApplyConfiguration {
	b.ApprovalReason = &value
	return b
}

// WithReasonEnded sets the ReasonEnded field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReasonEnded field is set to the value of the last call.
func (b *BreakglassSessionStatusApplyConfiguration) WithReasonEnded(value string) *BreakglassSessionStatusApplyConfiguration {
	b.ReasonEnded = &value
	return b
}
