/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BreakglassEscalationSpecApplyConfiguration represents a declarative configuration of the BreakglassEscalationSpec type for use
// with apply.
//
// BreakglassEscalationSpec defines the desired state of BreakglassEscalation.
type BreakglassEscalationSpecApplyConfiguration struct {
	// allowed specifies who is allowed to use this escalation.
	Allowed *BreakglassEscalationAllowedApplyConfiguration `json:"allowed,omitempty"`
	// approvers specifies who is allowed to approve this escalation.
	Approvers *BreakglassEscalationApproversApplyConfiguration `json:"approvers,omitempty"`
	// escalatedGroup is the group to be granted by this escalation.
	EscalatedGroup *string `json:"escalatedGroup,omitempty"`
	// maxValidFor is the maximum amount of time a session for this escalation will be active for after it is approved.
	MaxValidFor *string `json:"maxValidFor,omitempty"`
	// retainFor is the amount of time to wait before removing a session for this escalation after it expired
	RetainFor *string `json:"retainFor,omitempty"`
	// approvalTimeout is the maximum amount of time allowed for an approver to approve a session for this escalation.
	// If this duration elapses without approval, the session expires and transitions to ApprovalTimeout state.
	ApprovalTimeout *string `json:"approvalTimeout,omitempty"`
	// clusterConfigRefs lists ClusterConfig object names this escalation applies to (alternative to allowed.clusters).
	ClusterConfigRefs []string `json:"clusterConfigRefs,omitempty"`
	// denyPolicyRefs (optional) attach default deny policies to any session created via this escalation.
	DenyPolicyRefs []string `json:"denyPolicyRefs,omitempty"`
	// requestReason configures an optional free-text reason the requester must or may provide
	// when creating a session for this escalation. If omitted, no reason is requested.
	RequestReason *ReasonConfigApplyConfiguration `json:"requestReason,omitempty"`
	// approvalReason configures an optional free-text reason the approver must or may provide
	// when approving/rejecting a session for this escalation. If omitted, no approver reason is requested.
	ApprovalReason *ReasonConfigApplyConfiguration `json:"approvalReason,omitempty"`
	// allowedApproverDomains can restrict approvers to specific email domains for this escalation.
	// If omitted, cluster-level defaults are used.
	AllowedApproverDomains []string `json:"allowedApproverDomains,omitempty"`
	// allowedIdentityProviders specifies which IdentityProvider CRs can use this escalation.
	// If empty or unset, the escalation accepts any IdentityProvider allowed by the cluster
	// (from ClusterConfig.IdentityProviderRefs, or all enabled providers if cluster is unrestricted).
	// If set, only users authenticated via one of the named providers can use this escalation.
	// Names should match the metadata.name of IdentityProvider resources.
	// The intersection of cluster-allowed and escalation-allowed IDPs is used.
	// NOTE: This field is mutually exclusive with AllowedIdentityProvidersForRequests and AllowedIdentityProvidersForApprovers.
	AllowedIdentityProviders []string `json:"allowedIdentityProviders,omitempty"`
	// allowedIdentityProvidersForRequests specifies which IdentityProvider CRs can REQUEST this escalation.
	// If empty, defaults to AllowedIdentityProviders (or cluster defaults if that is also unset).
	// If set, only users authenticated via one of the named providers can request this escalation.
	// This field is mutually exclusive with AllowedIdentityProviders.
	// When set, AllowedIdentityProvidersForApprovers must also be set (or both can be left empty).
	AllowedIdentityProvidersForRequests []string `json:"allowedIdentityProvidersForRequests,omitempty"`
	// allowedIdentityProvidersForApprovers specifies which IdentityProvider CRs can APPROVE this escalation.
	// If empty, defaults to AllowedIdentityProviders (or cluster defaults if that is also unset).
	// If set, only users authenticated via one of the named providers can approve this escalation.
	// This field is mutually exclusive with AllowedIdentityProviders.
	// When set, AllowedIdentityProvidersForRequests must also be set (or both can be left empty).
	AllowedIdentityProvidersForApprovers []string `json:"allowedIdentityProvidersForApprovers,omitempty"`
	// blockSelfApproval, if set to true, will prevent the session requester from approving their own session for this escalation.
	// If omitted (nil), the cluster-level setting will be used.
	BlockSelfApproval *bool `json:"blockSelfApproval,omitempty"`
	// disableNotifications, if set to true, will disable email notifications for sessions created via this escalation.
	// Approvers will not receive emails when sessions are requested, approved, or rejected.
	// Default: false (notifications are enabled by default)
	DisableNotifications *bool `json:"disableNotifications,omitempty"`
	// notificationExclusions allows excluding specific users or groups from receiving email notifications for this escalation.
	// This is useful for excluding automated users or specific groups from notification spam.
	NotificationExclusions *NotificationExclusionsApplyConfiguration `json:"notificationExclusions,omitempty"`
	// mailProvider specifies which MailProvider to use for email notifications for this escalation.
	// If empty, falls back to the cluster's MailProvider, then to the default MailProvider.
	MailProvider *string `json:"mailProvider,omitempty"`
	// podSecurityOverrides allows this escalation to relax pod security rules from DenyPolicy.
	// When a user has an active session with this escalation and attempts to exec into a pod,
	// these overrides are applied to the pod security evaluation.
	// This enables trusted groups (e.g., SRE) to access high-risk pods when necessary.
	PodSecurityOverrides *PodSecurityOverridesApplyConfiguration `json:"podSecurityOverrides,omitempty"`
}

// BreakglassEscalationSpecApplyConfiguration constructs a declarative configuration of the BreakglassEscalationSpec type for use with
// apply.
func BreakglassEscalationSpec() *BreakglassEscalationSpecApplyConfiguration {
	return &BreakglassEscalationSpecApplyConfiguration{}
}

// WithAllowed sets the Allowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allowed field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithAllowed(value *BreakglassEscalationAllowedApplyConfiguration) *BreakglassEscalationSpecApplyConfiguration {
	b.Allowed = value
	return b
}

// WithApprovers sets the Approvers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Approvers field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithApprovers(value *BreakglassEscalationApproversApplyConfiguration) *BreakglassEscalationSpecApplyConfiguration {
	b.Approvers = value
	return b
}

// WithEscalatedGroup sets the EscalatedGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EscalatedGroup field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithEscalatedGroup(value string) *BreakglassEscalationSpecApplyConfiguration {
	b.EscalatedGroup = &value
	return b
}

// WithMaxValidFor sets the MaxValidFor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxValidFor field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithMaxValidFor(value string) *BreakglassEscalationSpecApplyConfiguration {
	b.MaxValidFor = &value
	return b
}

// WithRetainFor sets the RetainFor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetainFor field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithRetainFor(value string) *BreakglassEscalationSpecApplyConfiguration {
	b.RetainFor = &value
	return b
}

// WithApprovalTimeout sets the ApprovalTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovalTimeout field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithApprovalTimeout(value string) *BreakglassEscalationSpecApplyConfiguration {
	b.ApprovalTimeout = &value
	return b
}

// WithClusterConfigRefs adds the given value to the ClusterConfigRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ClusterConfigRefs field.
func (b *BreakglassEscalationSpecApplyConfiguration) WithClusterConfigRefs(values ...string) *BreakglassEscalationSpecApplyConfiguration {
	for i := range values {
		b.ClusterConfigRefs = append(b.ClusterConfigRefs, values[i])
	}
	return b
}

// WithDenyPolicyRefs adds the given value to the DenyPolicyRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DenyPolicyRefs field.
func (b *BreakglassEscalationSpecApplyConfiguration) WithDenyPolicyRefs(values ...string) *BreakglassEscalationSpecApplyConfiguration {
	for i := range values {
		b.DenyPolicyRefs = append(b.DenyPolicyRefs, values[i])
	}
	return b
}

// WithRequestReason sets the RequestReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestReason field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithRequestReason(value *ReasonConfigApplyConfiguration) *BreakglassEscalationSpecApplyConfiguration {
	b.RequestReason = value
	return b
}

// WithApprovalReason sets the ApprovalReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovalReason field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithApprovalReason(value *ReasonConfigApplyConfiguration) *BreakglassEscalationSpecApplyConfiguration {
	b.ApprovalReason = value
	return b
}

// WithAllowedApproverDomains adds the given value to the AllowedApproverDomains field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedApproverDomains field.
func (b *BreakglassEscalationSpecApplyConfiguration) WithAllowedApproverDomains(values ...string) *BreakglassEscalationSpecApplyConfiguration {
	for i := range values {
		b.AllowedApproverDomains = append(b.AllowedApproverDomains, values[i])
	}
	return b
}

// WithAllowedIdentityProviders adds the given value to the AllowedIdentityProviders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedIdentityProviders field.
func (b *BreakglassEscalationSpecApplyConfiguration) WithAllowedIdentityProviders(values ...string) *BreakglassEscalationSpecApplyConfiguration {
	for i := range values {
		b.AllowedIdentityProviders = append(b.AllowedIdentityProviders, values[i])
	}
	return b
}

// WithAllowedIdentityProvidersForRequests adds the given value to the AllowedIdentityProvidersForRequests field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedIdentityProvidersForRequests field.
func (b *BreakglassEscalationSpecApplyConfiguration) WithAllowedIdentityProvidersForRequests(values ...string) *BreakglassEscalationSpecApplyConfiguration {
	for i := range values {
		b.AllowedIdentityProvidersForRequests = append(b.AllowedIdentityProvidersForRequests, values[i])
	}
	return b
}

// WithAllowedIdentityProvidersForApprovers adds the given value to the AllowedIdentityProvidersForApprovers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedIdentityProvidersForApprovers field.
func (b *BreakglassEscalationSpecApplyConfiguration) WithAllowedIdentityProvidersForApprovers(values ...string) *BreakglassEscalationSpecApplyConfiguration {
	for i := range values {
		b.AllowedIdentityProvidersForApprovers = append(b.AllowedIdentityProvidersForApprovers, values[i])
	}
	return b
}

// WithBlockSelfApproval sets the BlockSelfApproval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlockSelfApproval field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithBlockSelfApproval(value bool) *BreakglassEscalationSpecApplyConfiguration {
	b.BlockSelfApproval = &value
	return b
}

// WithDisableNotifications sets the DisableNotifications field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableNotifications field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithDisableNotifications(value bool) *BreakglassEscalationSpecApplyConfiguration {
	b.DisableNotifications = &value
	return b
}

// WithNotificationExclusions sets the NotificationExclusions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotificationExclusions field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithNotificationExclusions(value *NotificationExclusionsApplyConfiguration) *BreakglassEscalationSpecApplyConfiguration {
	b.NotificationExclusions = value
	return b
}

// WithMailProvider sets the MailProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MailProvider field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithMailProvider(value string) *BreakglassEscalationSpecApplyConfiguration {
	b.MailProvider = &value
	return b
}

// WithPodSecurityOverrides sets the PodSecurityOverrides field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSecurityOverrides field is set to the value of the last call.
func (b *BreakglassEscalationSpecApplyConfiguration) WithPodSecurityOverrides(value *PodSecurityOverridesApplyConfiguration) *BreakglassEscalationSpecApplyConfiguration {
	b.PodSecurityOverrides = value
	return b
}
