/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterConfigStatusApplyConfiguration represents a declarative configuration of the ClusterConfigStatus type for use
// with apply.
//
// ClusterConfigStatus captures readiness of the cluster configuration.
type ClusterConfigStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation of the most recently observed ClusterConfig
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions track ClusterConfig state (kubeconfig validation, connection status, etc.)
	// All status information is conveyed through conditions.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ClusterConfigStatusApplyConfiguration constructs a declarative configuration of the ClusterConfigStatus type for use with
// apply.
func ClusterConfigStatus() *ClusterConfigStatusApplyConfiguration {
	return &ClusterConfigStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ClusterConfigStatusApplyConfiguration) WithObservedGeneration(value int64) *ClusterConfigStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ClusterConfigStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ClusterConfigStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
