/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen-cached. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DebugSessionArtifactStatusApplyConfiguration represents a declarative configuration of the DebugSessionArtifactStatus type for use
// with apply.
//
// DebugSessionArtifactStatus is safe to expose to API readers. Provider
// object keys, URLs, version IDs, credentials, and secret references are not
// persisted here.
type DebugSessionArtifactStatusApplyConfiguration struct {
	// state is the monotonic lifecycle state.
	State *apiv1alpha1.ArtifactLifecycleState `json:"state,omitempty"`
	// lifecycleRevision is the CAS revision for durable state transitions.
	LifecycleRevision *int64 `json:"lifecycleRevision,omitempty"`
	// observedGeneration is the last processed object generation.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// size is the validated compressed archive size.
	Size *int64 `json:"size,omitempty"`
	// sha256 is the validated compressed archive digest.
	SHA256 *string `json:"sha256,omitempty"`
	// createdAt records artifact admission.
	CreatedAt *v1.Time `json:"createdAt,omitempty"`
	// availableAt records successful validated upload.
	AvailableAt *v1.Time `json:"availableAt,omitempty"`
	// deletedAt records successful exact-version cleanup.
	DeletedAt *v1.Time `json:"deletedAt,omitempty"`
	// outbox is the bounded provider operation state.
	Outbox *ArtifactOutboxStatusApplyConfiguration `json:"outbox,omitempty"`
	// cleanupAmbiguous requires operator/reconciler evidence before finalization.
	CleanupAmbiguous *bool `json:"cleanupAmbiguous,omitempty"`
	// conditions contain bounded lifecycle evidence.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// DebugSessionArtifactStatusApplyConfiguration constructs a declarative configuration of the DebugSessionArtifactStatus type for use with
// apply.
func DebugSessionArtifactStatus() *DebugSessionArtifactStatusApplyConfiguration {
	return &DebugSessionArtifactStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithState(value apiv1alpha1.ArtifactLifecycleState) *DebugSessionArtifactStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithLifecycleRevision sets the LifecycleRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleRevision field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithLifecycleRevision(value int64) *DebugSessionArtifactStatusApplyConfiguration {
	b.LifecycleRevision = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithObservedGeneration(value int64) *DebugSessionArtifactStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithSize(value int64) *DebugSessionArtifactStatusApplyConfiguration {
	b.Size = &value
	return b
}

// WithSHA256 sets the SHA256 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SHA256 field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithSHA256(value string) *DebugSessionArtifactStatusApplyConfiguration {
	b.SHA256 = &value
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithCreatedAt(value v1.Time) *DebugSessionArtifactStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithAvailableAt sets the AvailableAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableAt field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithAvailableAt(value v1.Time) *DebugSessionArtifactStatusApplyConfiguration {
	b.AvailableAt = &value
	return b
}

// WithDeletedAt sets the DeletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletedAt field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithDeletedAt(value v1.Time) *DebugSessionArtifactStatusApplyConfiguration {
	b.DeletedAt = &value
	return b
}

// WithOutbox sets the Outbox field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Outbox field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithOutbox(value *ArtifactOutboxStatusApplyConfiguration) *DebugSessionArtifactStatusApplyConfiguration {
	b.Outbox = value
	return b
}

// WithCleanupAmbiguous sets the CleanupAmbiguous field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CleanupAmbiguous field is set to the value of the last call.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithCleanupAmbiguous(value bool) *DebugSessionArtifactStatusApplyConfiguration {
	b.CleanupAmbiguous = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DebugSessionArtifactStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *DebugSessionArtifactStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
