/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugResourceQuotaConfigApplyConfiguration represents a declarative configuration of the DebugResourceQuotaConfig type for use
// with apply.
//
// DebugResourceQuotaConfig specifies resource limits for debug sessions.
type DebugResourceQuotaConfigApplyConfiguration struct {
	// maxPods limits the maximum number of debug pods per session.
	MaxPods *int32 `json:"maxPods,omitempty"`
	// maxCPU limits the total CPU across all debug pods.
	// Uses Kubernetes resource quantity format (e.g., "2", "500m").
	MaxCPU *string `json:"maxCPU,omitempty"`
	// maxMemory limits the total memory across all debug pods.
	// Uses Kubernetes resource quantity format (e.g., "1Gi", "512Mi").
	MaxMemory *string `json:"maxMemory,omitempty"`
	// maxStorage limits ephemeral storage for debug pods.
	MaxStorage *string `json:"maxStorage,omitempty"`
	// enforceResourceRequests requires resource requests on all containers.
	EnforceResourceRequests *bool `json:"enforceResourceRequests,omitempty"`
	// enforceResourceLimits requires resource limits on all containers.
	EnforceResourceLimits *bool `json:"enforceResourceLimits,omitempty"`
}

// DebugResourceQuotaConfigApplyConfiguration constructs a declarative configuration of the DebugResourceQuotaConfig type for use with
// apply.
func DebugResourceQuotaConfig() *DebugResourceQuotaConfigApplyConfiguration {
	return &DebugResourceQuotaConfigApplyConfiguration{}
}

// WithMaxPods sets the MaxPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPods field is set to the value of the last call.
func (b *DebugResourceQuotaConfigApplyConfiguration) WithMaxPods(value int32) *DebugResourceQuotaConfigApplyConfiguration {
	b.MaxPods = &value
	return b
}

// WithMaxCPU sets the MaxCPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCPU field is set to the value of the last call.
func (b *DebugResourceQuotaConfigApplyConfiguration) WithMaxCPU(value string) *DebugResourceQuotaConfigApplyConfiguration {
	b.MaxCPU = &value
	return b
}

// WithMaxMemory sets the MaxMemory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMemory field is set to the value of the last call.
func (b *DebugResourceQuotaConfigApplyConfiguration) WithMaxMemory(value string) *DebugResourceQuotaConfigApplyConfiguration {
	b.MaxMemory = &value
	return b
}

// WithMaxStorage sets the MaxStorage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxStorage field is set to the value of the last call.
func (b *DebugResourceQuotaConfigApplyConfiguration) WithMaxStorage(value string) *DebugResourceQuotaConfigApplyConfiguration {
	b.MaxStorage = &value
	return b
}

// WithEnforceResourceRequests sets the EnforceResourceRequests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnforceResourceRequests field is set to the value of the last call.
func (b *DebugResourceQuotaConfigApplyConfiguration) WithEnforceResourceRequests(value bool) *DebugResourceQuotaConfigApplyConfiguration {
	b.EnforceResourceRequests = &value
	return b
}

// WithEnforceResourceLimits sets the EnforceResourceLimits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnforceResourceLimits field is set to the value of the last call.
func (b *DebugResourceQuotaConfigApplyConfiguration) WithEnforceResourceLimits(value bool) *DebugResourceQuotaConfigApplyConfiguration {
	b.EnforceResourceLimits = &value
	return b
}
