/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugPodTemplateReferenceApplyConfiguration represents a declarative configuration of the DebugPodTemplateReference type for use
// with apply.
//
// DebugPodTemplateReference references a DebugPodTemplate.
type DebugPodTemplateReferenceApplyConfiguration struct {
	// name is the name of the DebugPodTemplate to reference.
	Name *string `json:"name,omitempty"`
}

// DebugPodTemplateReferenceApplyConfiguration constructs a declarative configuration of the DebugPodTemplateReference type for use with
// apply.
func DebugPodTemplateReference() *DebugPodTemplateReferenceApplyConfiguration {
	return &DebugPodTemplateReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DebugPodTemplateReferenceApplyConfiguration) WithName(value string) *DebugPodTemplateReferenceApplyConfiguration {
	b.Name = &value
	return b
}
