/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugPodSpecApplyConfiguration represents a declarative configuration of the DebugPodSpec type for use
// with apply.
//
// DebugPodSpec defines the pod specification for debug containers.
// This is a subset of corev1.PodSpec with fields relevant to debugging.
type DebugPodSpecApplyConfiguration struct {
	// metadata contains labels and annotations for the pod.
	Metadata *DebugPodMetadataApplyConfiguration `json:"metadata,omitempty"`
	// spec contains the pod specification.
	Spec *DebugPodSpecInnerApplyConfiguration `json:"spec,omitempty"`
}

// DebugPodSpecApplyConfiguration constructs a declarative configuration of the DebugPodSpec type for use with
// apply.
func DebugPodSpec() *DebugPodSpecApplyConfiguration {
	return &DebugPodSpecApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *DebugPodSpecApplyConfiguration) WithMetadata(value *DebugPodMetadataApplyConfiguration) *DebugPodSpecApplyConfiguration {
	b.Metadata = value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *DebugPodSpecApplyConfiguration) WithSpec(value *DebugPodSpecInnerApplyConfiguration) *DebugPodSpecApplyConfiguration {
	b.Spec = value
	return b
}
