/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugSessionApproversApplyConfiguration represents a declarative configuration of the DebugSessionApprovers type for use
// with apply.
//
// DebugSessionApprovers configures the approval workflow.
type DebugSessionApproversApplyConfiguration struct {
	// groups specifies groups that can approve debug sessions.
	Groups []string `json:"groups,omitempty"`
	// users specifies individual users that can approve debug sessions.
	Users []string `json:"users,omitempty"`
	// autoApproveFor specifies conditions for auto-approval.
	AutoApproveFor *AutoApproveConfigApplyConfiguration `json:"autoApproveFor,omitempty"`
}

// DebugSessionApproversApplyConfiguration constructs a declarative configuration of the DebugSessionApprovers type for use with
// apply.
func DebugSessionApprovers() *DebugSessionApproversApplyConfiguration {
	return &DebugSessionApproversApplyConfiguration{}
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *DebugSessionApproversApplyConfiguration) WithGroups(values ...string) *DebugSessionApproversApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *DebugSessionApproversApplyConfiguration) WithUsers(values ...string) *DebugSessionApproversApplyConfiguration {
	for i := range values {
		b.Users = append(b.Users, values[i])
	}
	return b
}

// WithAutoApproveFor sets the AutoApproveFor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoApproveFor field is set to the value of the last call.
func (b *DebugSessionApproversApplyConfiguration) WithAutoApproveFor(value *AutoApproveConfigApplyConfiguration) *DebugSessionApproversApplyConfiguration {
	b.AutoApproveFor = value
	return b
}
