/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugPodSpecOverridesApplyConfiguration represents a declarative configuration of the DebugPodSpecOverrides type for use
// with apply.
//
// DebugPodSpecOverrides defines overridable pod spec fields.
type DebugPodSpecOverridesApplyConfiguration struct {
	// hostNetwork overrides the hostNetwork setting.
	HostNetwork *bool `json:"hostNetwork,omitempty"`
	// hostPID overrides the hostPID setting.
	HostPID *bool `json:"hostPID,omitempty"`
	// hostIPC overrides the hostIPC setting.
	HostIPC *bool `json:"hostIPC,omitempty"`
	// containers contains container-level overrides.
	Containers []DebugContainerOverrideApplyConfiguration `json:"containers,omitempty"`
}

// DebugPodSpecOverridesApplyConfiguration constructs a declarative configuration of the DebugPodSpecOverrides type for use with
// apply.
func DebugPodSpecOverrides() *DebugPodSpecOverridesApplyConfiguration {
	return &DebugPodSpecOverridesApplyConfiguration{}
}

// WithHostNetwork sets the HostNetwork field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostNetwork field is set to the value of the last call.
func (b *DebugPodSpecOverridesApplyConfiguration) WithHostNetwork(value bool) *DebugPodSpecOverridesApplyConfiguration {
	b.HostNetwork = &value
	return b
}

// WithHostPID sets the HostPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPID field is set to the value of the last call.
func (b *DebugPodSpecOverridesApplyConfiguration) WithHostPID(value bool) *DebugPodSpecOverridesApplyConfiguration {
	b.HostPID = &value
	return b
}

// WithHostIPC sets the HostIPC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostIPC field is set to the value of the last call.
func (b *DebugPodSpecOverridesApplyConfiguration) WithHostIPC(value bool) *DebugPodSpecOverridesApplyConfiguration {
	b.HostIPC = &value
	return b
}

// WithContainers adds the given value to the Containers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Containers field.
func (b *DebugPodSpecOverridesApplyConfiguration) WithContainers(values ...*DebugContainerOverrideApplyConfiguration) *DebugPodSpecOverridesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithContainers")
		}
		b.Containers = append(b.Containers, *values[i])
	}
	return b
}
