/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugSessionAuditConfigApplyConfiguration represents a declarative configuration of the DebugSessionAuditConfig type for use
// with apply.
//
// DebugSessionAuditConfig configures audit logging.
type DebugSessionAuditConfigApplyConfiguration struct {
	// enabled enables audit logging for debug sessions.
	Enabled *bool `json:"enabled,omitempty"`
	// destinations specifies where audit events are sent.
	Destinations []AuditDestinationApplyConfiguration `json:"destinations,omitempty"`
	// enableTerminalRecording enables recording of terminal sessions.
	EnableTerminalRecording *bool `json:"enableTerminalRecording,omitempty"`
	// recordingRetention specifies how long recordings are kept.
	RecordingRetention *string `json:"recordingRetention,omitempty"`
	// enableShellHistory enables shell command history capture.
	EnableShellHistory *bool `json:"enableShellHistory,omitempty"`
}

// DebugSessionAuditConfigApplyConfiguration constructs a declarative configuration of the DebugSessionAuditConfig type for use with
// apply.
func DebugSessionAuditConfig() *DebugSessionAuditConfigApplyConfiguration {
	return &DebugSessionAuditConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DebugSessionAuditConfigApplyConfiguration) WithEnabled(value bool) *DebugSessionAuditConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithDestinations adds the given value to the Destinations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Destinations field.
func (b *DebugSessionAuditConfigApplyConfiguration) WithDestinations(values ...*AuditDestinationApplyConfiguration) *DebugSessionAuditConfigApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDestinations")
		}
		b.Destinations = append(b.Destinations, *values[i])
	}
	return b
}

// WithEnableTerminalRecording sets the EnableTerminalRecording field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableTerminalRecording field is set to the value of the last call.
func (b *DebugSessionAuditConfigApplyConfiguration) WithEnableTerminalRecording(value bool) *DebugSessionAuditConfigApplyConfiguration {
	b.EnableTerminalRecording = &value
	return b
}

// WithRecordingRetention sets the RecordingRetention field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecordingRetention field is set to the value of the last call.
func (b *DebugSessionAuditConfigApplyConfiguration) WithRecordingRetention(value string) *DebugSessionAuditConfigApplyConfiguration {
	b.RecordingRetention = &value
	return b
}

// WithEnableShellHistory sets the EnableShellHistory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnableShellHistory field is set to the value of the last call.
func (b *DebugSessionAuditConfigApplyConfiguration) WithEnableShellHistory(value bool) *DebugSessionAuditConfigApplyConfiguration {
	b.EnableShellHistory = &value
	return b
}
