/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugPodTemplateSpecApplyConfiguration represents a declarative configuration of the DebugPodTemplateSpec type for use
// with apply.
//
// DebugPodTemplateSpec defines the desired state of DebugPodTemplate.
// It contains a reusable pod specification for debug sessions.
type DebugPodTemplateSpecApplyConfiguration struct {
	// displayName is a human-readable name for this template.
	DisplayName *string `json:"displayName,omitempty"`
	// description provides detailed information about what this template does.
	Description *string `json:"description,omitempty"`
	// template defines the pod specification that will be used to create debug pods.
	// This spec is rendered into DaemonSet/Deployment by DebugSessionTemplate.
	Template *DebugPodSpecApplyConfiguration `json:"template,omitempty"`
}

// DebugPodTemplateSpecApplyConfiguration constructs a declarative configuration of the DebugPodTemplateSpec type for use with
// apply.
func DebugPodTemplateSpec() *DebugPodTemplateSpecApplyConfiguration {
	return &DebugPodTemplateSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *DebugPodTemplateSpecApplyConfiguration) WithDisplayName(value string) *DebugPodTemplateSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DebugPodTemplateSpecApplyConfiguration) WithDescription(value string) *DebugPodTemplateSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *DebugPodTemplateSpecApplyConfiguration) WithTemplate(value *DebugPodSpecApplyConfiguration) *DebugPodTemplateSpecApplyConfiguration {
	b.Template = value
	return b
}
