/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// DebugSessionTemplateSpecApplyConfiguration represents a declarative configuration of the DebugSessionTemplateSpec type for use
// with apply.
//
// DebugSessionTemplateSpec defines the desired state of DebugSessionTemplate.
type DebugSessionTemplateSpecApplyConfiguration struct {
	// displayName is a human-readable name for this template.
	DisplayName *string `json:"displayName,omitempty"`
	// description provides detailed information about what this template does.
	Description *string `json:"description,omitempty"`
	// mode specifies the debug session mode: "workload", "kubectl-debug", or "hybrid".
	// Defaults to "workload" for backward compatibility.
	Mode *apiv1alpha1.DebugSessionTemplateMode `json:"mode,omitempty"`
	// podTemplateRef references a DebugPodTemplate for the pod specification.
	// Required when mode is "workload" or "hybrid".
	PodTemplateRef *DebugPodTemplateReferenceApplyConfiguration `json:"podTemplateRef,omitempty"`
	// workloadType specifies the type of workload to create (DaemonSet or Deployment).
	// Required when mode is "workload" or "hybrid".
	WorkloadType *apiv1alpha1.DebugWorkloadType `json:"workloadType,omitempty"`
	// replicas specifies the number of replicas for Deployment workloads.
	// Defaults to 1. Ignored for DaemonSet workloads.
	Replicas *int32 `json:"replicas,omitempty"`
	// podOverrides allows overriding specific fields in the referenced pod template.
	// Merged with the base template using strategic merge patch.
	PodOverrides *DebugPodOverridesApplyConfiguration `json:"podOverrides,omitempty"`
	// affinityOverrides adds or replaces affinity rules from the pod template.
	AffinityOverrides *v1.Affinity `json:"affinityOverrides,omitempty"`
	// additionalTolerations adds tolerations to those defined in the pod template.
	AdditionalTolerations []v1.Toleration `json:"additionalTolerations,omitempty"`
	// schedulingConstraints defines mandatory scheduling rules for debug pods.
	// These constraints are applied AFTER template settings and CANNOT be overridden by users.
	SchedulingConstraints *SchedulingConstraintsApplyConfiguration `json:"schedulingConstraints,omitempty"`
	// schedulingOptions offers users a choice of predefined scheduling configurations.
	// Each option can define different node selectors, affinities, etc.
	SchedulingOptions *SchedulingOptionsApplyConfiguration `json:"schedulingOptions,omitempty"`
	// kubectlDebug configures kubectl debug operations.
	// Required when mode is "kubectl-debug" or "hybrid".
	KubectlDebug *KubectlDebugConfigApplyConfiguration `json:"kubectlDebug,omitempty"`
	// allowed specifies who can request this debug template and on which clusters.
	Allowed *DebugSessionAllowedApplyConfiguration `json:"allowed,omitempty"`
	// approvers configures approval workflow for debug session requests.
	// If omitted, sessions are auto-approved for users in the allowed groups.
	Approvers *DebugSessionApproversApplyConfiguration `json:"approvers,omitempty"`
	// constraints defines session duration and usage limits.
	Constraints *DebugSessionConstraintsApplyConfiguration `json:"constraints,omitempty"`
	// targetNamespace specifies the namespace where debug pods are deployed.
	// Must be pre-created by an administrator.
	TargetNamespace *string `json:"targetNamespace,omitempty"`
	// namespaceConstraints defines where debug pods can be deployed.
	// Allows user choice within administrator-defined boundaries.
	NamespaceConstraints *NamespaceConstraintsApplyConfiguration `json:"namespaceConstraints,omitempty"`
	// impersonation controls which identity is used to deploy debug resources.
	// Enables least-privilege deployment using a constrained ServiceAccount.
	Impersonation *ImpersonationConfigApplyConfiguration `json:"impersonation,omitempty"`
	// failMode specifies behavior when namespace doesn't exist or deployment fails.
	// "closed" (default) denies the session, "open" allows without deployed pods.
	FailMode *string `json:"failMode,omitempty"`
	// terminalSharing configures collaborative terminal sessions.
	TerminalSharing *TerminalSharingConfigApplyConfiguration `json:"terminalSharing,omitempty"`
	// audit configures audit logging for debug sessions.
	Audit *DebugSessionAuditConfigApplyConfiguration `json:"audit,omitempty"`
	// auxiliaryResources defines additional Kubernetes resources to deploy with the debug session.
	// These resources are created/deleted alongside the debug pods.
	AuxiliaryResources []AuxiliaryResourceApplyConfiguration `json:"auxiliaryResources,omitempty"`
	// auxiliaryResourceDefaults sets default enabled/disabled state for auxiliary resource categories.
	// Key is the category name, value is whether it's enabled by default.
	AuxiliaryResourceDefaults map[string]bool `json:"auxiliaryResourceDefaults,omitempty"`
	// requiredAuxiliaryResourceCategories lists categories that MUST be enabled.
	// These cannot be disabled by bindings or users.
	RequiredAuxiliaryResourceCategories []string `json:"requiredAuxiliaryResourceCategories,omitempty"`
	// notification configures notification settings for debug sessions using this template.
	Notification *DebugSessionNotificationConfigApplyConfiguration `json:"notification,omitempty"`
	// requestReason configures reason requirements for debug session requests.
	RequestReason *DebugRequestReasonConfigApplyConfiguration `json:"requestReason,omitempty"`
	// approvalReason configures reason requirements for approval/rejection actions.
	ApprovalReason *DebugApprovalReasonConfigApplyConfiguration `json:"approvalReason,omitempty"`
	// resourceQuota specifies resource limits for debug sessions using this template.
	// Helps prevent resource exhaustion on target clusters.
	ResourceQuota *DebugResourceQuotaConfigApplyConfiguration `json:"resourceQuota,omitempty"`
	// podDisruptionBudget configures disruption tolerance for debug pods.
	// Useful for long-running debug sessions that shouldn't be evicted.
	PodDisruptionBudget *DebugPDBConfigApplyConfiguration `json:"podDisruptionBudget,omitempty"`
	// labels are additional labels applied to all resources created by this template.
	Labels map[string]string `json:"labels,omitempty"`
	// annotations are additional annotations applied to all resources created by this template.
	Annotations map[string]string `json:"annotations,omitempty"`
	// priority controls the order in which templates are displayed in the UI.
	// Higher values appear first. Defaults to 0.
	Priority *int32 `json:"priority,omitempty"`
	// hidden hides this template from the UI but allows API usage.
	// Useful for templates used by automation or internal tools.
	Hidden *bool `json:"hidden,omitempty"`
	// deprecated marks this template as deprecated.
	// Deprecated templates show a warning but can still be used.
	Deprecated *bool `json:"deprecated,omitempty"`
	// deprecationMessage explains why this template is deprecated and suggests alternatives.
	// Only displayed when deprecated is true.
	DeprecationMessage *string `json:"deprecationMessage,omitempty"`
	// expirationBehavior controls what happens when a session expires.
	// Options: "terminate" (default) or "notify-only".
	ExpirationBehavior *string `json:"expirationBehavior,omitempty"`
	// gracePeriodBeforeExpiry is the duration before expiry when users are notified.
	// Users will receive a warning notification at this interval before session expires.
	GracePeriodBeforeExpiry *string `json:"gracePeriodBeforeExpiry,omitempty"`
}

// DebugSessionTemplateSpecApplyConfiguration constructs a declarative configuration of the DebugSessionTemplateSpec type for use with
// apply.
func DebugSessionTemplateSpec() *DebugSessionTemplateSpecApplyConfiguration {
	return &DebugSessionTemplateSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithDisplayName(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithDescription(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithMode(value apiv1alpha1.DebugSessionTemplateMode) *DebugSessionTemplateSpecApplyConfiguration {
	b.Mode = &value
	return b
}

// WithPodTemplateRef sets the PodTemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplateRef field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithPodTemplateRef(value *DebugPodTemplateReferenceApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.PodTemplateRef = value
	return b
}

// WithWorkloadType sets the WorkloadType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadType field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithWorkloadType(value apiv1alpha1.DebugWorkloadType) *DebugSessionTemplateSpecApplyConfiguration {
	b.WorkloadType = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithReplicas(value int32) *DebugSessionTemplateSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithPodOverrides sets the PodOverrides field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodOverrides field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithPodOverrides(value *DebugPodOverridesApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.PodOverrides = value
	return b
}

// WithAffinityOverrides sets the AffinityOverrides field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AffinityOverrides field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAffinityOverrides(value v1.Affinity) *DebugSessionTemplateSpecApplyConfiguration {
	b.AffinityOverrides = &value
	return b
}

// WithAdditionalTolerations adds the given value to the AdditionalTolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalTolerations field.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAdditionalTolerations(values ...v1.Toleration) *DebugSessionTemplateSpecApplyConfiguration {
	for i := range values {
		b.AdditionalTolerations = append(b.AdditionalTolerations, values[i])
	}
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithSchedulingConstraints(value *SchedulingConstraintsApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.SchedulingConstraints = value
	return b
}

// WithSchedulingOptions sets the SchedulingOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingOptions field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithSchedulingOptions(value *SchedulingOptionsApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.SchedulingOptions = value
	return b
}

// WithKubectlDebug sets the KubectlDebug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubectlDebug field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithKubectlDebug(value *KubectlDebugConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.KubectlDebug = value
	return b
}

// WithAllowed sets the Allowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allowed field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAllowed(value *DebugSessionAllowedApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.Allowed = value
	return b
}

// WithApprovers sets the Approvers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Approvers field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithApprovers(value *DebugSessionApproversApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.Approvers = value
	return b
}

// WithConstraints sets the Constraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Constraints field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithConstraints(value *DebugSessionConstraintsApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.Constraints = value
	return b
}

// WithTargetNamespace sets the TargetNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetNamespace field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithTargetNamespace(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.TargetNamespace = &value
	return b
}

// WithNamespaceConstraints sets the NamespaceConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceConstraints field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithNamespaceConstraints(value *NamespaceConstraintsApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.NamespaceConstraints = value
	return b
}

// WithImpersonation sets the Impersonation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Impersonation field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithImpersonation(value *ImpersonationConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.Impersonation = value
	return b
}

// WithFailMode sets the FailMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailMode field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithFailMode(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.FailMode = &value
	return b
}

// WithTerminalSharing sets the TerminalSharing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminalSharing field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithTerminalSharing(value *TerminalSharingConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.TerminalSharing = value
	return b
}

// WithAudit sets the Audit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Audit field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAudit(value *DebugSessionAuditConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.Audit = value
	return b
}

// WithAuxiliaryResources adds the given value to the AuxiliaryResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuxiliaryResources field.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAuxiliaryResources(values ...*AuxiliaryResourceApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAuxiliaryResources")
		}
		b.AuxiliaryResources = append(b.AuxiliaryResources, *values[i])
	}
	return b
}

// WithAuxiliaryResourceDefaults puts the entries into the AuxiliaryResourceDefaults field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AuxiliaryResourceDefaults field,
// overwriting an existing map entries in AuxiliaryResourceDefaults field with the same key.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAuxiliaryResourceDefaults(entries map[string]bool) *DebugSessionTemplateSpecApplyConfiguration {
	if b.AuxiliaryResourceDefaults == nil && len(entries) > 0 {
		b.AuxiliaryResourceDefaults = make(map[string]bool, len(entries))
	}
	for k, v := range entries {
		b.AuxiliaryResourceDefaults[k] = v
	}
	return b
}

// WithRequiredAuxiliaryResourceCategories adds the given value to the RequiredAuxiliaryResourceCategories field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RequiredAuxiliaryResourceCategories field.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithRequiredAuxiliaryResourceCategories(values ...string) *DebugSessionTemplateSpecApplyConfiguration {
	for i := range values {
		b.RequiredAuxiliaryResourceCategories = append(b.RequiredAuxiliaryResourceCategories, values[i])
	}
	return b
}

// WithNotification sets the Notification field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Notification field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithNotification(value *DebugSessionNotificationConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.Notification = value
	return b
}

// WithRequestReason sets the RequestReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestReason field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithRequestReason(value *DebugRequestReasonConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.RequestReason = value
	return b
}

// WithApprovalReason sets the ApprovalReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovalReason field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithApprovalReason(value *DebugApprovalReasonConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.ApprovalReason = value
	return b
}

// WithResourceQuota sets the ResourceQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceQuota field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithResourceQuota(value *DebugResourceQuotaConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.ResourceQuota = value
	return b
}

// WithPodDisruptionBudget sets the PodDisruptionBudget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodDisruptionBudget field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithPodDisruptionBudget(value *DebugPDBConfigApplyConfiguration) *DebugSessionTemplateSpecApplyConfiguration {
	b.PodDisruptionBudget = value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithLabels(entries map[string]string) *DebugSessionTemplateSpecApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithAnnotations(entries map[string]string) *DebugSessionTemplateSpecApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithPriority(value int32) *DebugSessionTemplateSpecApplyConfiguration {
	b.Priority = &value
	return b
}

// WithHidden sets the Hidden field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hidden field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithHidden(value bool) *DebugSessionTemplateSpecApplyConfiguration {
	b.Hidden = &value
	return b
}

// WithDeprecated sets the Deprecated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deprecated field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithDeprecated(value bool) *DebugSessionTemplateSpecApplyConfiguration {
	b.Deprecated = &value
	return b
}

// WithDeprecationMessage sets the DeprecationMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeprecationMessage field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithDeprecationMessage(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.DeprecationMessage = &value
	return b
}

// WithExpirationBehavior sets the ExpirationBehavior field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpirationBehavior field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithExpirationBehavior(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.ExpirationBehavior = &value
	return b
}

// WithGracePeriodBeforeExpiry sets the GracePeriodBeforeExpiry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GracePeriodBeforeExpiry field is set to the value of the last call.
func (b *DebugSessionTemplateSpecApplyConfiguration) WithGracePeriodBeforeExpiry(value string) *DebugSessionTemplateSpecApplyConfiguration {
	b.GracePeriodBeforeExpiry = &value
	return b
}
