/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// DebugContainerOverrideApplyConfiguration represents a declarative configuration of the DebugContainerOverride type for use
// with apply.
//
// DebugContainerOverride allows overriding container settings.
type DebugContainerOverrideApplyConfiguration struct {
	// name is the name of the container to override.
	Name *string `json:"name,omitempty"`
	// securityContext overrides the container's security context.
	SecurityContext *v1.SecurityContext `json:"securityContext,omitempty"`
	// resources overrides the container's resource requirements.
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// env adds environment variables to the container.
	Env []v1.EnvVar `json:"env,omitempty"`
}

// DebugContainerOverrideApplyConfiguration constructs a declarative configuration of the DebugContainerOverride type for use with
// apply.
func DebugContainerOverride() *DebugContainerOverrideApplyConfiguration {
	return &DebugContainerOverrideApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DebugContainerOverrideApplyConfiguration) WithName(value string) *DebugContainerOverrideApplyConfiguration {
	b.Name = &value
	return b
}

// WithSecurityContext sets the SecurityContext field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityContext field is set to the value of the last call.
func (b *DebugContainerOverrideApplyConfiguration) WithSecurityContext(value v1.SecurityContext) *DebugContainerOverrideApplyConfiguration {
	b.SecurityContext = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *DebugContainerOverrideApplyConfiguration) WithResources(value v1.ResourceRequirements) *DebugContainerOverrideApplyConfiguration {
	b.Resources = &value
	return b
}

// WithEnv adds the given value to the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Env field.
func (b *DebugContainerOverrideApplyConfiguration) WithEnv(values ...v1.EnvVar) *DebugContainerOverrideApplyConfiguration {
	for i := range values {
		b.Env = append(b.Env, values[i])
	}
	return b
}
