/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugSessionAllowedApplyConfiguration represents a declarative configuration of the DebugSessionAllowed type for use
// with apply.
//
// DebugSessionAllowed specifies who can request debug sessions.
type DebugSessionAllowedApplyConfiguration struct {
	// groups specifies groups that can request this template.
	Groups []string `json:"groups,omitempty"`
	// users specifies individual users that can request this template.
	Users []string `json:"users,omitempty"`
	// clusters specifies which clusters this template can be used on.
	// Supports glob patterns.
	Clusters []string `json:"clusters,omitempty"`
}

// DebugSessionAllowedApplyConfiguration constructs a declarative configuration of the DebugSessionAllowed type for use with
// apply.
func DebugSessionAllowed() *DebugSessionAllowedApplyConfiguration {
	return &DebugSessionAllowedApplyConfiguration{}
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *DebugSessionAllowedApplyConfiguration) WithGroups(values ...string) *DebugSessionAllowedApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *DebugSessionAllowedApplyConfiguration) WithUsers(values ...string) *DebugSessionAllowedApplyConfiguration {
	for i := range values {
		b.Users = append(b.Users, values[i])
	}
	return b
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *DebugSessionAllowedApplyConfiguration) WithClusters(values ...string) *DebugSessionAllowedApplyConfiguration {
	for i := range values {
		b.Clusters = append(b.Clusters, values[i])
	}
	return b
}
