/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DebugSessionStatusApplyConfiguration represents a declarative configuration of the DebugSessionStatus type for use
// with apply.
//
// DebugSessionStatus defines the observed state of DebugSession.
type DebugSessionStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation of the most recently observed DebugSession.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// state is the current state of the debug session.
	State *apiv1alpha1.DebugSessionState `json:"state,omitempty"`
	// approval tracks approval information.
	Approval *DebugSessionApprovalApplyConfiguration `json:"approval,omitempty"`
	// participants lists users currently in the session.
	Participants []DebugSessionParticipantApplyConfiguration `json:"participants,omitempty"`
	// terminalSharing contains terminal sharing information.
	TerminalSharing *TerminalSharingStatusApplyConfiguration `json:"terminalSharing,omitempty"`
	// deployedResources lists resources created on the target cluster.
	DeployedResources []DeployedResourceRefApplyConfiguration `json:"deployedResources,omitempty"`
	// allowedPods lists pods that users can exec into via this session.
	// Dynamically updated as debug pods start/stop.
	AllowedPods []AllowedPodRefApplyConfiguration `json:"allowedPods,omitempty"`
	// allowedPodOperations caches the resolved pod operations from the template.
	// Used by the webhook to determine which operations are permitted.
	AllowedPodOperations *AllowedPodOperationsApplyConfiguration `json:"allowedPodOperations,omitempty"`
	// kubectlDebugStatus tracks kubectl debug operations for kubectl-debug mode.
	KubectlDebugStatus *KubectlDebugStatusApplyConfiguration `json:"kubectlDebugStatus,omitempty"`
	// startsAt is when the session became active.
	StartsAt *v1.Time `json:"startsAt,omitempty"`
	// expiresAt is when the session will expire.
	ExpiresAt *v1.Time `json:"expiresAt,omitempty"`
	// renewalCount tracks how many times the session has been renewed.
	RenewalCount *int32 `json:"renewalCount,omitempty"`
	// conditions provide detailed status information.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// message provides human-readable status information.
	Message *string `json:"message,omitempty"`
	// resolvedTemplate caches the resolved DebugSessionTemplate spec.
	// Used to ensure consistent behavior even if template changes.
	ResolvedTemplate *DebugSessionTemplateSpecApplyConfiguration `json:"resolvedTemplate,omitempty"`
	// resolvedBinding caches information about the binding used (if any).
	ResolvedBinding *ResolvedBindingRefApplyConfiguration `json:"resolvedBinding,omitempty"`
	// auxiliaryResourceStatuses tracks the state of deployed auxiliary resources.
	AuxiliaryResourceStatuses []AuxiliaryResourceStatusApplyConfiguration `json:"auxiliaryResourceStatuses,omitempty"`
	// podTemplateResourceStatuses tracks the state of additional resources deployed
	// from multi-document pod templates. These are K8s resources defined in second+
	// documents of a pod templateString (first document is always the PodSpec).
	PodTemplateResourceStatuses []PodTemplateResourceStatusApplyConfiguration `json:"podTemplateResourceStatuses,omitempty"`
}

// DebugSessionStatusApplyConfiguration constructs a declarative configuration of the DebugSessionStatus type for use with
// apply.
func DebugSessionStatus() *DebugSessionStatusApplyConfiguration {
	return &DebugSessionStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithObservedGeneration(value int64) *DebugSessionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithState(value apiv1alpha1.DebugSessionState) *DebugSessionStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithApproval sets the Approval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Approval field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithApproval(value *DebugSessionApprovalApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	b.Approval = value
	return b
}

// WithParticipants adds the given value to the Participants field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Participants field.
func (b *DebugSessionStatusApplyConfiguration) WithParticipants(values ...*DebugSessionParticipantApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithParticipants")
		}
		b.Participants = append(b.Participants, *values[i])
	}
	return b
}

// WithTerminalSharing sets the TerminalSharing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TerminalSharing field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithTerminalSharing(value *TerminalSharingStatusApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	b.TerminalSharing = value
	return b
}

// WithDeployedResources adds the given value to the DeployedResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DeployedResources field.
func (b *DebugSessionStatusApplyConfiguration) WithDeployedResources(values ...*DeployedResourceRefApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDeployedResources")
		}
		b.DeployedResources = append(b.DeployedResources, *values[i])
	}
	return b
}

// WithAllowedPods adds the given value to the AllowedPods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedPods field.
func (b *DebugSessionStatusApplyConfiguration) WithAllowedPods(values ...*AllowedPodRefApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllowedPods")
		}
		b.AllowedPods = append(b.AllowedPods, *values[i])
	}
	return b
}

// WithAllowedPodOperations sets the AllowedPodOperations field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedPodOperations field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithAllowedPodOperations(value *AllowedPodOperationsApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	b.AllowedPodOperations = value
	return b
}

// WithKubectlDebugStatus sets the KubectlDebugStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubectlDebugStatus field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithKubectlDebugStatus(value *KubectlDebugStatusApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	b.KubectlDebugStatus = value
	return b
}

// WithStartsAt sets the StartsAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartsAt field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithStartsAt(value v1.Time) *DebugSessionStatusApplyConfiguration {
	b.StartsAt = &value
	return b
}

// WithExpiresAt sets the ExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiresAt field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithExpiresAt(value v1.Time) *DebugSessionStatusApplyConfiguration {
	b.ExpiresAt = &value
	return b
}

// WithRenewalCount sets the RenewalCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewalCount field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithRenewalCount(value int32) *DebugSessionStatusApplyConfiguration {
	b.RenewalCount = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DebugSessionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithMessage(value string) *DebugSessionStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithResolvedTemplate sets the ResolvedTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResolvedTemplate field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithResolvedTemplate(value *DebugSessionTemplateSpecApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	b.ResolvedTemplate = value
	return b
}

// WithResolvedBinding sets the ResolvedBinding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResolvedBinding field is set to the value of the last call.
func (b *DebugSessionStatusApplyConfiguration) WithResolvedBinding(value *ResolvedBindingRefApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	b.ResolvedBinding = value
	return b
}

// WithAuxiliaryResourceStatuses adds the given value to the AuxiliaryResourceStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuxiliaryResourceStatuses field.
func (b *DebugSessionStatusApplyConfiguration) WithAuxiliaryResourceStatuses(values ...*AuxiliaryResourceStatusApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAuxiliaryResourceStatuses")
		}
		b.AuxiliaryResourceStatuses = append(b.AuxiliaryResourceStatuses, *values[i])
	}
	return b
}

// WithPodTemplateResourceStatuses adds the given value to the PodTemplateResourceStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodTemplateResourceStatuses field.
func (b *DebugSessionStatusApplyConfiguration) WithPodTemplateResourceStatuses(values ...*PodTemplateResourceStatusApplyConfiguration) *DebugSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPodTemplateResourceStatuses")
		}
		b.PodTemplateResourceStatuses = append(b.PodTemplateResourceStatuses, *values[i])
	}
	return b
}
