/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen-cached. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	internal "github.com/telekom/k8s-breakglass/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DebugSessionArtifactApplyConfiguration represents a declarative configuration of the DebugSessionArtifact type for use
// with apply.
type DebugSessionArtifactApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration    `json:",inline"`
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                             *DebugSessionArtifactSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                           *DebugSessionArtifactStatusApplyConfiguration `json:"status,omitempty"`
}

// DebugSessionArtifact constructs a declarative configuration of the DebugSessionArtifact type for use with
// apply.
func DebugSessionArtifact(name, namespace string) *DebugSessionArtifactApplyConfiguration {
	b := &DebugSessionArtifactApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("DebugSessionArtifact")
	b.WithAPIVersion("breakglass.t-caas.telekom.com/v1alpha1")
	return b
}

// ExtractDebugSessionArtifactFrom extracts the applied configuration owned by fieldManager from
// debugSessionArtifact for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// debugSessionArtifact must be a unmodified DebugSessionArtifact API object that was retrieved from the Kubernetes API.
// ExtractDebugSessionArtifactFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDebugSessionArtifactFrom(debugSessionArtifact *apiv1alpha1.DebugSessionArtifact, fieldManager string, subresource string) (*DebugSessionArtifactApplyConfiguration, error) {
	b := &DebugSessionArtifactApplyConfiguration{}
	err := managedfields.ExtractInto(debugSessionArtifact, internal.Parser().Type("com.github.telekom.k8s-breakglass.api.v1alpha1.DebugSessionArtifact"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(debugSessionArtifact.Name)
	b.WithNamespace(debugSessionArtifact.Namespace)

	b.WithKind("DebugSessionArtifact")
	b.WithAPIVersion("breakglass.t-caas.telekom.com/v1alpha1")
	return b, nil
}

// ExtractDebugSessionArtifact extracts the applied configuration owned by fieldManager from
// debugSessionArtifact. If no managedFields are found in debugSessionArtifact for fieldManager, a
// DebugSessionArtifactApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// debugSessionArtifact must be a unmodified DebugSessionArtifact API object that was retrieved from the Kubernetes API.
// ExtractDebugSessionArtifact provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractDebugSessionArtifact(debugSessionArtifact *apiv1alpha1.DebugSessionArtifact, fieldManager string) (*DebugSessionArtifactApplyConfiguration, error) {
	return ExtractDebugSessionArtifactFrom(debugSessionArtifact, fieldManager, "")
}

// ExtractDebugSessionArtifactStatus extracts the applied configuration owned by fieldManager from
// debugSessionArtifact for the status subresource.
func ExtractDebugSessionArtifactStatus(debugSessionArtifact *apiv1alpha1.DebugSessionArtifact, fieldManager string) (*DebugSessionArtifactApplyConfiguration, error) {
	return ExtractDebugSessionArtifactFrom(debugSessionArtifact, fieldManager, "status")
}

func (b DebugSessionArtifactApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithKind(value string) *DebugSessionArtifactApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithAPIVersion(value string) *DebugSessionArtifactApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithName(value string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithGenerateName(value string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithNamespace(value string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithUID(value types.UID) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithResourceVersion(value string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithGeneration(value int64) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithCreationTimestamp(value metav1.Time) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *DebugSessionArtifactApplyConfiguration) WithLabels(entries map[string]string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *DebugSessionArtifactApplyConfiguration) WithAnnotations(entries map[string]string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *DebugSessionArtifactApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *DebugSessionArtifactApplyConfiguration) WithFinalizers(values ...string) *DebugSessionArtifactApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *DebugSessionArtifactApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithSpec(value *DebugSessionArtifactSpecApplyConfiguration) *DebugSessionArtifactApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *DebugSessionArtifactApplyConfiguration) WithStatus(value *DebugSessionArtifactStatusApplyConfiguration) *DebugSessionArtifactApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *DebugSessionArtifactApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *DebugSessionArtifactApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *DebugSessionArtifactApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *DebugSessionArtifactApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
