/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DebugSessionParticipantApplyConfiguration represents a declarative configuration of the DebugSessionParticipant type for use
// with apply.
//
// DebugSessionParticipant represents a user in the session.
type DebugSessionParticipantApplyConfiguration struct {
	// user is the username/identifier of the participant.
	User *string `json:"user,omitempty"`
	// email is the email address of the participant (from OIDC "email" claim).
	// Used for sending email notifications.
	Email *string `json:"email,omitempty"`
	// displayName is the human-readable name of the participant (from OIDC "name" claim).
	DisplayName *string `json:"displayName,omitempty"`
	// role is the participant's role (owner or participant).
	Role *apiv1alpha1.ParticipantRole `json:"role,omitempty"`
	// joinedAt is when the user joined the session.
	JoinedAt *v1.Time `json:"joinedAt,omitempty"`
	// leftAt is when the user left the session (if they have left).
	LeftAt *v1.Time `json:"leftAt,omitempty"`
}

// DebugSessionParticipantApplyConfiguration constructs a declarative configuration of the DebugSessionParticipant type for use with
// apply.
func DebugSessionParticipant() *DebugSessionParticipantApplyConfiguration {
	return &DebugSessionParticipantApplyConfiguration{}
}

// WithUser sets the User field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the User field is set to the value of the last call.
func (b *DebugSessionParticipantApplyConfiguration) WithUser(value string) *DebugSessionParticipantApplyConfiguration {
	b.User = &value
	return b
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *DebugSessionParticipantApplyConfiguration) WithEmail(value string) *DebugSessionParticipantApplyConfiguration {
	b.Email = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *DebugSessionParticipantApplyConfiguration) WithDisplayName(value string) *DebugSessionParticipantApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithRole sets the Role field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Role field is set to the value of the last call.
func (b *DebugSessionParticipantApplyConfiguration) WithRole(value apiv1alpha1.ParticipantRole) *DebugSessionParticipantApplyConfiguration {
	b.Role = &value
	return b
}

// WithJoinedAt sets the JoinedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JoinedAt field is set to the value of the last call.
func (b *DebugSessionParticipantApplyConfiguration) WithJoinedAt(value v1.Time) *DebugSessionParticipantApplyConfiguration {
	b.JoinedAt = &value
	return b
}

// WithLeftAt sets the LeftAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LeftAt field is set to the value of the last call.
func (b *DebugSessionParticipantApplyConfiguration) WithLeftAt(value v1.Time) *DebugSessionParticipantApplyConfiguration {
	b.LeftAt = &value
	return b
}
