/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugPDBConfigApplyConfiguration represents a declarative configuration of the DebugPDBConfig type for use
// with apply.
//
// DebugPDBConfig configures PodDisruptionBudget settings.
type DebugPDBConfigApplyConfiguration struct {
	// enabled creates a PDB for debug pods.
	Enabled *bool `json:"enabled,omitempty"`
	// minAvailable specifies the minimum number of debug pods that must be available.
	MinAvailable *int32 `json:"minAvailable,omitempty"`
	// maxUnavailable specifies the maximum number of debug pods that can be unavailable.
	MaxUnavailable *int32 `json:"maxUnavailable,omitempty"`
}

// DebugPDBConfigApplyConfiguration constructs a declarative configuration of the DebugPDBConfig type for use with
// apply.
func DebugPDBConfig() *DebugPDBConfigApplyConfiguration {
	return &DebugPDBConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DebugPDBConfigApplyConfiguration) WithEnabled(value bool) *DebugPDBConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithMinAvailable sets the MinAvailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinAvailable field is set to the value of the last call.
func (b *DebugPDBConfigApplyConfiguration) WithMinAvailable(value int32) *DebugPDBConfigApplyConfiguration {
	b.MinAvailable = &value
	return b
}

// WithMaxUnavailable sets the MaxUnavailable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxUnavailable field is set to the value of the last call.
func (b *DebugPDBConfigApplyConfiguration) WithMaxUnavailable(value int32) *DebugPDBConfigApplyConfiguration {
	b.MaxUnavailable = &value
	return b
}
