/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DebugSessionConstraintsApplyConfiguration represents a declarative configuration of the DebugSessionConstraints type for use
// with apply.
//
// DebugSessionConstraints defines limits on debug sessions.
type DebugSessionConstraintsApplyConfiguration struct {
	// maxDuration is the maximum allowed session duration.
	MaxDuration *string `json:"maxDuration,omitempty"`
	// defaultDuration is the default session duration if not specified.
	DefaultDuration *string `json:"defaultDuration,omitempty"`
	// allowRenewal controls whether session renewal is permitted.
	// When nil, defaults to true. Set to false to disable renewals.
	AllowRenewal *bool `json:"allowRenewal,omitempty"`
	// maxRenewals is the maximum number of times a session can be renewed.
	// When nil, defaults to 3. Set to 0 to disallow renewals.
	// Ignored if allowRenewal is false.
	MaxRenewals *int32 `json:"maxRenewals,omitempty"`
	// renewalLimit is deprecated, use maxRenewals instead. Removal target: v1beta1.
	RenewalLimit *int32 `json:"renewalLimit,omitempty"`
	// maxConcurrentSessions limits concurrent debug sessions per cluster.
	MaxConcurrentSessions *int32 `json:"maxConcurrentSessions,omitempty"`
}

// DebugSessionConstraintsApplyConfiguration constructs a declarative configuration of the DebugSessionConstraints type for use with
// apply.
func DebugSessionConstraints() *DebugSessionConstraintsApplyConfiguration {
	return &DebugSessionConstraintsApplyConfiguration{}
}

// WithMaxDuration sets the MaxDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxDuration field is set to the value of the last call.
func (b *DebugSessionConstraintsApplyConfiguration) WithMaxDuration(value string) *DebugSessionConstraintsApplyConfiguration {
	b.MaxDuration = &value
	return b
}

// WithDefaultDuration sets the DefaultDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultDuration field is set to the value of the last call.
func (b *DebugSessionConstraintsApplyConfiguration) WithDefaultDuration(value string) *DebugSessionConstraintsApplyConfiguration {
	b.DefaultDuration = &value
	return b
}

// WithAllowRenewal sets the AllowRenewal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowRenewal field is set to the value of the last call.
func (b *DebugSessionConstraintsApplyConfiguration) WithAllowRenewal(value bool) *DebugSessionConstraintsApplyConfiguration {
	b.AllowRenewal = &value
	return b
}

// WithMaxRenewals sets the MaxRenewals field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRenewals field is set to the value of the last call.
func (b *DebugSessionConstraintsApplyConfiguration) WithMaxRenewals(value int32) *DebugSessionConstraintsApplyConfiguration {
	b.MaxRenewals = &value
	return b
}

// WithRenewalLimit sets the RenewalLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RenewalLimit field is set to the value of the last call.
func (b *DebugSessionConstraintsApplyConfiguration) WithRenewalLimit(value int32) *DebugSessionConstraintsApplyConfiguration {
	b.RenewalLimit = &value
	return b
}

// WithMaxConcurrentSessions sets the MaxConcurrentSessions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConcurrentSessions field is set to the value of the last call.
func (b *DebugSessionConstraintsApplyConfiguration) WithMaxConcurrentSessions(value int32) *DebugSessionConstraintsApplyConfiguration {
	b.MaxConcurrentSessions = &value
	return b
}
