/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DebugSessionApprovalApplyConfiguration represents a declarative configuration of the DebugSessionApproval type for use
// with apply.
//
// DebugSessionApproval tracks approval information.
type DebugSessionApprovalApplyConfiguration struct {
	// required indicates if approval is needed.
	Required *bool `json:"required,omitempty"`
	// approvedBy is the email/identifier of the approver.
	ApprovedBy *string `json:"approvedBy,omitempty"`
	// approvedAt is when the session was approved.
	ApprovedAt *v1.Time `json:"approvedAt,omitempty"`
	// rejectedBy is the email/identifier of the rejector.
	RejectedBy *string `json:"rejectedBy,omitempty"`
	// rejectedAt is when the session was rejected.
	RejectedAt *v1.Time `json:"rejectedAt,omitempty"`
	// reason is the reason for approval/rejection.
	Reason *string `json:"reason,omitempty"`
}

// DebugSessionApprovalApplyConfiguration constructs a declarative configuration of the DebugSessionApproval type for use with
// apply.
func DebugSessionApproval() *DebugSessionApprovalApplyConfiguration {
	return &DebugSessionApprovalApplyConfiguration{}
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *DebugSessionApprovalApplyConfiguration) WithRequired(value bool) *DebugSessionApprovalApplyConfiguration {
	b.Required = &value
	return b
}

// WithApprovedBy sets the ApprovedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovedBy field is set to the value of the last call.
func (b *DebugSessionApprovalApplyConfiguration) WithApprovedBy(value string) *DebugSessionApprovalApplyConfiguration {
	b.ApprovedBy = &value
	return b
}

// WithApprovedAt sets the ApprovedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApprovedAt field is set to the value of the last call.
func (b *DebugSessionApprovalApplyConfiguration) WithApprovedAt(value v1.Time) *DebugSessionApprovalApplyConfiguration {
	b.ApprovedAt = &value
	return b
}

// WithRejectedBy sets the RejectedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RejectedBy field is set to the value of the last call.
func (b *DebugSessionApprovalApplyConfiguration) WithRejectedBy(value string) *DebugSessionApprovalApplyConfiguration {
	b.RejectedBy = &value
	return b
}

// WithRejectedAt sets the RejectedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RejectedAt field is set to the value of the last call.
func (b *DebugSessionApprovalApplyConfiguration) WithRejectedAt(value v1.Time) *DebugSessionApprovalApplyConfiguration {
	b.RejectedAt = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *DebugSessionApprovalApplyConfiguration) WithReason(value string) *DebugSessionApprovalApplyConfiguration {
	b.Reason = &value
	return b
}
