/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DebugSessionClusterBindingStatusApplyConfiguration represents a declarative configuration of the DebugSessionClusterBindingStatus type for use
// with apply.
//
// DebugSessionClusterBindingStatus defines the observed state of DebugSessionClusterBinding.
type DebugSessionClusterBindingStatusApplyConfiguration struct {
	// conditions represent the latest available observations of the binding's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// observedGeneration is the generation last observed by the controller.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// resolvedTemplates lists the templates matched by this binding.
	ResolvedTemplates []ResolvedTemplateRefApplyConfiguration `json:"resolvedTemplates,omitempty"`
	// resolvedClusters lists the clusters matched by this binding.
	ResolvedClusters []ResolvedClusterRefApplyConfiguration `json:"resolvedClusters,omitempty"`
	// activeSessionCount is the number of active debug sessions using this binding.
	ActiveSessionCount *int32 `json:"activeSessionCount,omitempty"`
	// lastUsed is the timestamp of the last session created using this binding.
	LastUsed *metav1.Time `json:"lastUsed,omitempty"`
	// nameCollisions lists any detected name collisions with other bindings.
	// A collision occurs when the same template+cluster produces the same effective name.
	NameCollisions []NameCollisionApplyConfiguration `json:"nameCollisions,omitempty"`
}

// DebugSessionClusterBindingStatusApplyConfiguration constructs a declarative configuration of the DebugSessionClusterBindingStatus type for use with
// apply.
func DebugSessionClusterBindingStatus() *DebugSessionClusterBindingStatusApplyConfiguration {
	return &DebugSessionClusterBindingStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DebugSessionClusterBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithObservedGeneration(value int64) *DebugSessionClusterBindingStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithResolvedTemplates adds the given value to the ResolvedTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResolvedTemplates field.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithResolvedTemplates(values ...*ResolvedTemplateRefApplyConfiguration) *DebugSessionClusterBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResolvedTemplates")
		}
		b.ResolvedTemplates = append(b.ResolvedTemplates, *values[i])
	}
	return b
}

// WithResolvedClusters adds the given value to the ResolvedClusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResolvedClusters field.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithResolvedClusters(values ...*ResolvedClusterRefApplyConfiguration) *DebugSessionClusterBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithResolvedClusters")
		}
		b.ResolvedClusters = append(b.ResolvedClusters, *values[i])
	}
	return b
}

// WithActiveSessionCount sets the ActiveSessionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveSessionCount field is set to the value of the last call.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithActiveSessionCount(value int32) *DebugSessionClusterBindingStatusApplyConfiguration {
	b.ActiveSessionCount = &value
	return b
}

// WithLastUsed sets the LastUsed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUsed field is set to the value of the last call.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithLastUsed(value metav1.Time) *DebugSessionClusterBindingStatusApplyConfiguration {
	b.LastUsed = &value
	return b
}

// WithNameCollisions adds the given value to the NameCollisions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NameCollisions field.
func (b *DebugSessionClusterBindingStatusApplyConfiguration) WithNameCollisions(values ...*NameCollisionApplyConfiguration) *DebugSessionClusterBindingStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNameCollisions")
		}
		b.NameCollisions = append(b.NameCollisions, *values[i])
	}
	return b
}
