/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
)

// DebugSessionConnectionLeaseApplyConfiguration represents a declarative configuration of the DebugSessionConnectionLease type for use
// with apply.
//
// DebugSessionConnectionLease records the durable fencing identity for a
// controller-owned target connection.
type DebugSessionConnectionLeaseApplyConfiguration struct {
	Namespace     *string    `json:"namespace,omitempty"`
	Name          *string    `json:"name,omitempty"`
	UID           *types.UID `json:"uid,omitempty"`
	HolderUID     *types.UID `json:"holderUID,omitempty"`
	TargetUID     *types.UID `json:"targetUID,omitempty"`
	ProfileDigest *string    `json:"profileDigest,omitempty"`
	Epoch         *int64     `json:"epoch,omitempty"`
	ExpiresAt     *v1.Time   `json:"expiresAt,omitempty"`
}

// DebugSessionConnectionLeaseApplyConfiguration constructs a declarative configuration of the DebugSessionConnectionLease type for use with
// apply.
func DebugSessionConnectionLease() *DebugSessionConnectionLeaseApplyConfiguration {
	return &DebugSessionConnectionLeaseApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithNamespace(value string) *DebugSessionConnectionLeaseApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithName(value string) *DebugSessionConnectionLeaseApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithUID(value types.UID) *DebugSessionConnectionLeaseApplyConfiguration {
	b.UID = &value
	return b
}

// WithHolderUID sets the HolderUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HolderUID field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithHolderUID(value types.UID) *DebugSessionConnectionLeaseApplyConfiguration {
	b.HolderUID = &value
	return b
}

// WithTargetUID sets the TargetUID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetUID field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithTargetUID(value types.UID) *DebugSessionConnectionLeaseApplyConfiguration {
	b.TargetUID = &value
	return b
}

// WithProfileDigest sets the ProfileDigest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProfileDigest field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithProfileDigest(value string) *DebugSessionConnectionLeaseApplyConfiguration {
	b.ProfileDigest = &value
	return b
}

// WithEpoch sets the Epoch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Epoch field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithEpoch(value int64) *DebugSessionConnectionLeaseApplyConfiguration {
	b.Epoch = &value
	return b
}

// WithExpiresAt sets the ExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiresAt field is set to the value of the last call.
func (b *DebugSessionConnectionLeaseApplyConfiguration) WithExpiresAt(value v1.Time) *DebugSessionConnectionLeaseApplyConfiguration {
	b.ExpiresAt = &value
	return b
}
