/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DenyRuleApplyConfiguration represents a declarative configuration of the DenyRule type for use
// with apply.
//
// DenyRule blocks an action matching the attributes.
type DenyRuleApplyConfiguration struct {
	// verbs like get, list, watch, create, update, patch, delete, deletecollection
	Verbs []string `json:"verbs,omitempty"`
	// apiGroups for the resource ("" for core)
	APIGroups []string `json:"apiGroups,omitempty"`
	// resources names (plural). Use "*" for wildcard. Subresources are matched via subresource field.
	Resources []string `json:"resources,omitempty"`
	// namespaces supports patterns (glob-style) and label-based namespace selection.
	// Empty means cluster-scoped only resources.
	Namespaces *NamespaceFilterApplyConfiguration `json:"namespaces,omitempty"`
	// resourceNames are specific resource object names (supports wildcards). If empty matches any.
	ResourceNames []string `json:"resourceNames,omitempty"`
	// subresources (e.g. status). If empty matches none (only main resource). Use "*" for any.
	Subresources []string `json:"subresources,omitempty"`
}

// DenyRuleApplyConfiguration constructs a declarative configuration of the DenyRule type for use with
// apply.
func DenyRule() *DenyRuleApplyConfiguration {
	return &DenyRuleApplyConfiguration{}
}

// WithVerbs adds the given value to the Verbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Verbs field.
func (b *DenyRuleApplyConfiguration) WithVerbs(values ...string) *DenyRuleApplyConfiguration {
	for i := range values {
		b.Verbs = append(b.Verbs, values[i])
	}
	return b
}

// WithAPIGroups adds the given value to the APIGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the APIGroups field.
func (b *DenyRuleApplyConfiguration) WithAPIGroups(values ...string) *DenyRuleApplyConfiguration {
	for i := range values {
		b.APIGroups = append(b.APIGroups, values[i])
	}
	return b
}

// WithResources adds the given value to the Resources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Resources field.
func (b *DenyRuleApplyConfiguration) WithResources(values ...string) *DenyRuleApplyConfiguration {
	for i := range values {
		b.Resources = append(b.Resources, values[i])
	}
	return b
}

// WithNamespaces sets the Namespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespaces field is set to the value of the last call.
func (b *DenyRuleApplyConfiguration) WithNamespaces(value *NamespaceFilterApplyConfiguration) *DenyRuleApplyConfiguration {
	b.Namespaces = value
	return b
}

// WithResourceNames adds the given value to the ResourceNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResourceNames field.
func (b *DenyRuleApplyConfiguration) WithResourceNames(values ...string) *DenyRuleApplyConfiguration {
	for i := range values {
		b.ResourceNames = append(b.ResourceNames, values[i])
	}
	return b
}

// WithSubresources adds the given value to the Subresources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subresources field.
func (b *DenyRuleApplyConfiguration) WithSubresources(values ...string) *DenyRuleApplyConfiguration {
	for i := range values {
		b.Subresources = append(b.Subresources, values[i])
	}
	return b
}
