/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DenyPolicyScopeApplyConfiguration represents a declarative configuration of the DenyPolicyScope type for use
// with apply.
//
// DenyPolicyScope selects targets the policy applies to.
type DenyPolicyScopeApplyConfiguration struct {
	// clusters list exact clusterIDs.
	Clusters []string `json:"clusters,omitempty"`
	// tenants list tenant IDs.
	Tenants []string `json:"tenants,omitempty"`
	// sessions list specific BreakglassSession names.
	Sessions []string `json:"sessions,omitempty"`
}

// DenyPolicyScopeApplyConfiguration constructs a declarative configuration of the DenyPolicyScope type for use with
// apply.
func DenyPolicyScope() *DenyPolicyScopeApplyConfiguration {
	return &DenyPolicyScopeApplyConfiguration{}
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *DenyPolicyScopeApplyConfiguration) WithClusters(values ...string) *DenyPolicyScopeApplyConfiguration {
	for i := range values {
		b.Clusters = append(b.Clusters, values[i])
	}
	return b
}

// WithTenants adds the given value to the Tenants field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tenants field.
func (b *DenyPolicyScopeApplyConfiguration) WithTenants(values ...string) *DenyPolicyScopeApplyConfiguration {
	for i := range values {
		b.Tenants = append(b.Tenants, values[i])
	}
	return b
}

// WithSessions adds the given value to the Sessions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sessions field.
func (b *DenyPolicyScopeApplyConfiguration) WithSessions(values ...string) *DenyPolicyScopeApplyConfiguration {
	for i := range values {
		b.Sessions = append(b.Sessions, values[i])
	}
	return b
}
