/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EphemeralContainerRefApplyConfiguration represents a declarative configuration of the EphemeralContainerRef type for use
// with apply.
//
// EphemeralContainerRef tracks an injected ephemeral container.
type EphemeralContainerRefApplyConfiguration struct {
	// podName is the name of the pod.
	PodName *string `json:"podName,omitempty"`
	// namespace is the pod's namespace.
	Namespace *string `json:"namespace,omitempty"`
	// containerName is the name of the ephemeral container.
	ContainerName *string `json:"containerName,omitempty"`
	// image is the container image.
	Image *string `json:"image,omitempty"`
	// injectedAt is when the container was injected.
	InjectedAt *v1.Time `json:"injectedAt,omitempty"`
	// injectedBy is who injected the container.
	InjectedBy *string `json:"injectedBy,omitempty"`
}

// EphemeralContainerRefApplyConfiguration constructs a declarative configuration of the EphemeralContainerRef type for use with
// apply.
func EphemeralContainerRef() *EphemeralContainerRefApplyConfiguration {
	return &EphemeralContainerRefApplyConfiguration{}
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *EphemeralContainerRefApplyConfiguration) WithPodName(value string) *EphemeralContainerRefApplyConfiguration {
	b.PodName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *EphemeralContainerRefApplyConfiguration) WithNamespace(value string) *EphemeralContainerRefApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithContainerName sets the ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerName field is set to the value of the last call.
func (b *EphemeralContainerRefApplyConfiguration) WithContainerName(value string) *EphemeralContainerRefApplyConfiguration {
	b.ContainerName = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *EphemeralContainerRefApplyConfiguration) WithImage(value string) *EphemeralContainerRefApplyConfiguration {
	b.Image = &value
	return b
}

// WithInjectedAt sets the InjectedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InjectedAt field is set to the value of the last call.
func (b *EphemeralContainerRefApplyConfiguration) WithInjectedAt(value v1.Time) *EphemeralContainerRefApplyConfiguration {
	b.InjectedAt = &value
	return b
}

// WithInjectedBy sets the InjectedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InjectedBy field is set to the value of the last call.
func (b *EphemeralContainerRefApplyConfiguration) WithInjectedBy(value string) *EphemeralContainerRefApplyConfiguration {
	b.InjectedBy = &value
	return b
}
