/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
)

// ImpersonationDenyRuleApplyConfiguration represents a declarative configuration of the ImpersonationDenyRule type for use
// with apply.
//
// ImpersonationDenyRule blocks impersonation matching the given attributes.
//
// An empty rule ({}) denies ALL impersonation — legacy and constrained, every
// mode, every identity, every action. That is the intended way to write "this
// cluster does not do impersonation".
type ImpersonationDenyRuleApplyConfiguration struct {
	// modes restricts the rule to specific impersonation modes.
	// Valid values: user-info, serviceaccount, arbitrary-node, associated-node, legacy.
	// If empty, the rule matches every mode.
	//
	// Include "legacy" to close the fallback escape hatch. Denying only the
	// constrained modes accomplishes nothing on a cluster that still carries a
	// blanket `impersonate` grant, because the API server falls back to it.
	Modes []apiv1alpha1.ImpersonationMode `json:"modes,omitempty"`
	// identityResources restricts the rule to specific identity resource kinds.
	// Valid values: users, groups, uids, userextras, serviceaccounts, nodes.
	// If empty, the rule matches every kind.
	IdentityResources []string `json:"identityResources,omitempty"`
	// identities restricts the rule to specific impersonation targets: usernames,
	// group names, UIDs, node names, ServiceAccount names or extra values.
	// Supports glob-style wildcards. If empty, the rule matches any target.
	//
	// Note that the API server collapses per-item checks into a single "*" check
	// once a request names four or more items, so a wildcard entry here is what
	// catches those requests.
	Identities []string `json:"identities,omitempty"`
	// namespaces restricts the rule to ServiceAccount identity checks in matching
	// namespaces. Only meaningful for the serviceaccounts identity resource, which
	// is the sole namespaced identity kind.
	Namespaces *NamespaceFilterApplyConfiguration `json:"namespaces,omitempty"`
	// extraKeys restricts the rule to userextras checks for specific extra keys.
	// Supports glob-style wildcards. Only meaningful with the userextras identity
	// resource.
	ExtraKeys []string `json:"extraKeys,omitempty"`
	// actionVerbs restricts the rule to `impersonate-on:<mode>:<verb>` action
	// checks for the named underlying verbs (get, list, create, …). Use "*" to
	// match any. If empty, the rule does not consider action checks at all unless
	// no other action-specific field is set.
	//
	// Cannot be combined with identities: the API server issues the identity and
	// action checks as two separate authorization requests, so no single request
	// carries both an impersonation target and an underlying verb.
	ActionVerbs []string `json:"actionVerbs,omitempty"`
	// targetResources restricts action checks to the resources being acted on
	// under impersonation (the target request's own resources). Supports "*".
	// Only meaningful together with actionVerbs.
	TargetResources []string `json:"targetResources,omitempty"`
	// targetAPIGroups restricts action checks to the target request's API groups.
	// Use "" for the core group and "*" for any. Only meaningful with actionVerbs.
	TargetAPIGroups []string `json:"targetAPIGroups,omitempty"`
	// reason is returned to the user when this rule denies. If empty, breakglass
	// generates a description of what was denied.
	Reason *string `json:"reason,omitempty"`
}

// ImpersonationDenyRuleApplyConfiguration constructs a declarative configuration of the ImpersonationDenyRule type for use with
// apply.
func ImpersonationDenyRule() *ImpersonationDenyRuleApplyConfiguration {
	return &ImpersonationDenyRuleApplyConfiguration{}
}

// WithModes adds the given value to the Modes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Modes field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithModes(values ...apiv1alpha1.ImpersonationMode) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.Modes = append(b.Modes, values[i])
	}
	return b
}

// WithIdentityResources adds the given value to the IdentityResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the IdentityResources field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithIdentityResources(values ...string) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.IdentityResources = append(b.IdentityResources, values[i])
	}
	return b
}

// WithIdentities adds the given value to the Identities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Identities field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithIdentities(values ...string) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.Identities = append(b.Identities, values[i])
	}
	return b
}

// WithNamespaces sets the Namespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespaces field is set to the value of the last call.
func (b *ImpersonationDenyRuleApplyConfiguration) WithNamespaces(value *NamespaceFilterApplyConfiguration) *ImpersonationDenyRuleApplyConfiguration {
	b.Namespaces = value
	return b
}

// WithExtraKeys adds the given value to the ExtraKeys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExtraKeys field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithExtraKeys(values ...string) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.ExtraKeys = append(b.ExtraKeys, values[i])
	}
	return b
}

// WithActionVerbs adds the given value to the ActionVerbs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActionVerbs field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithActionVerbs(values ...string) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.ActionVerbs = append(b.ActionVerbs, values[i])
	}
	return b
}

// WithTargetResources adds the given value to the TargetResources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetResources field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithTargetResources(values ...string) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.TargetResources = append(b.TargetResources, values[i])
	}
	return b
}

// WithTargetAPIGroups adds the given value to the TargetAPIGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetAPIGroups field.
func (b *ImpersonationDenyRuleApplyConfiguration) WithTargetAPIGroups(values ...string) *ImpersonationDenyRuleApplyConfiguration {
	for i := range values {
		b.TargetAPIGroups = append(b.TargetAPIGroups, values[i])
	}
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ImpersonationDenyRuleApplyConfiguration) WithReason(value string) *ImpersonationDenyRuleApplyConfiguration {
	b.Reason = &value
	return b
}
