/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ImpersonationConfigApplyConfiguration represents a declarative configuration of the ImpersonationConfig type for use
// with apply.
//
// ImpersonationConfig controls which identity is used to deploy debug resources.
// This enables least-privilege deployment where the controller impersonates
// a constrained ServiceAccount rather than using its own permissions.
type ImpersonationConfigApplyConfiguration struct {
	// serviceAccountRef references an existing ServiceAccount to impersonate.
	// The breakglass controller must have impersonation permissions for this SA.
	ServiceAccountRef *ServiceAccountReferenceApplyConfiguration `json:"serviceAccountRef,omitempty"`
}

// ImpersonationConfigApplyConfiguration constructs a declarative configuration of the ImpersonationConfig type for use with
// apply.
func ImpersonationConfig() *ImpersonationConfigApplyConfiguration {
	return &ImpersonationConfigApplyConfiguration{}
}

// WithServiceAccountRef sets the ServiceAccountRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountRef field is set to the value of the last call.
func (b *ImpersonationConfigApplyConfiguration) WithServiceAccountRef(value *ServiceAccountReferenceApplyConfiguration) *ImpersonationConfigApplyConfiguration {
	b.ServiceAccountRef = value
	return b
}
