/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// KeycloakGroupSyncApplyConfiguration represents a declarative configuration of the KeycloakGroupSync type for use
// with apply.
//
// KeycloakGroupSync holds Keycloak-specific group synchronization configuration
type KeycloakGroupSyncApplyConfiguration struct {
	// BaseURL is the Keycloak server URL
	// Example: https://keycloak.example.com
	BaseURL *string `json:"baseURL,omitempty"`
	// Realm is the Keycloak realm name
	Realm *string `json:"realm,omitempty"`
	// ClientID is the service account client ID for group/user queries (should have view-users/view-groups only)
	ClientID *string `json:"clientID,omitempty"`
	// ClientSecretRef references a Secret containing the client secret
	ClientSecretRef *SecretKeyReferenceApplyConfiguration `json:"clientSecretRef,omitempty"`
	// CacheTTL is the duration to cache user/group memberships (default: 10m)
	CacheTTL *string `json:"cacheTTL,omitempty"`
	// RequestTimeout is the timeout for Keycloak API requests (default: 10s)
	RequestTimeout *string `json:"requestTimeout,omitempty"`
	// InsecureSkipVerify allows skipping TLS verification (NOT for production!)
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
	// CertificateAuthority contains a PEM encoded CA certificate for TLS validation
	CertificateAuthority *string `json:"certificateAuthority,omitempty"`
}

// KeycloakGroupSyncApplyConfiguration constructs a declarative configuration of the KeycloakGroupSync type for use with
// apply.
func KeycloakGroupSync() *KeycloakGroupSyncApplyConfiguration {
	return &KeycloakGroupSyncApplyConfiguration{}
}

// WithBaseURL sets the BaseURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseURL field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithBaseURL(value string) *KeycloakGroupSyncApplyConfiguration {
	b.BaseURL = &value
	return b
}

// WithRealm sets the Realm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Realm field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithRealm(value string) *KeycloakGroupSyncApplyConfiguration {
	b.Realm = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithClientID(value string) *KeycloakGroupSyncApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecretRef sets the ClientSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecretRef field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithClientSecretRef(value *SecretKeyReferenceApplyConfiguration) *KeycloakGroupSyncApplyConfiguration {
	b.ClientSecretRef = value
	return b
}

// WithCacheTTL sets the CacheTTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CacheTTL field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithCacheTTL(value string) *KeycloakGroupSyncApplyConfiguration {
	b.CacheTTL = &value
	return b
}

// WithRequestTimeout sets the RequestTimeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestTimeout field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithRequestTimeout(value string) *KeycloakGroupSyncApplyConfiguration {
	b.RequestTimeout = &value
	return b
}

// WithInsecureSkipVerify sets the InsecureSkipVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureSkipVerify field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithInsecureSkipVerify(value bool) *KeycloakGroupSyncApplyConfiguration {
	b.InsecureSkipVerify = &value
	return b
}

// WithCertificateAuthority sets the CertificateAuthority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateAuthority field is set to the value of the last call.
func (b *KeycloakGroupSyncApplyConfiguration) WithCertificateAuthority(value string) *KeycloakGroupSyncApplyConfiguration {
	b.CertificateAuthority = &value
	return b
}
