/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// KubernetesSinkSpecApplyConfiguration represents a declarative configuration of the KubernetesSinkSpec type for use
// with apply.
//
// KubernetesSinkSpec configures the Kubernetes Event audit sink.
type KubernetesSinkSpecApplyConfiguration struct {
	// EventTypes limits which audit events create K8s Events.
	// Empty means use sensible defaults (session/escalation events only).
	EventTypes []string `json:"eventTypes,omitempty"`
}

// KubernetesSinkSpecApplyConfiguration constructs a declarative configuration of the KubernetesSinkSpec type for use with
// apply.
func KubernetesSinkSpec() *KubernetesSinkSpecApplyConfiguration {
	return &KubernetesSinkSpecApplyConfiguration{}
}

// WithEventTypes adds the given value to the EventTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EventTypes field.
func (b *KubernetesSinkSpecApplyConfiguration) WithEventTypes(values ...string) *KubernetesSinkSpecApplyConfiguration {
	for i := range values {
		b.EventTypes = append(b.EventTypes, values[i])
	}
	return b
}
