/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// KubectlDebugOperationTargetPodApplyConfiguration represents a declarative configuration of the KubectlDebugOperationTargetPod type for use
// with apply.
//
// KubectlDebugOperationTargetPod identifies a target Pod for durable
// operation recovery.
type KubectlDebugOperationTargetPodApplyConfiguration struct {
	// namespace is the Pod namespace.
	Namespace *string `json:"namespace,omitempty"`
	// name is the Pod name.
	Name *string `json:"name,omitempty"`
	// uid is the immutable Pod UID observed before the mutation.
	UID *types.UID `json:"uid,omitempty"`
}

// KubectlDebugOperationTargetPodApplyConfiguration constructs a declarative configuration of the KubectlDebugOperationTargetPod type for use with
// apply.
func KubectlDebugOperationTargetPod() *KubectlDebugOperationTargetPodApplyConfiguration {
	return &KubectlDebugOperationTargetPodApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *KubectlDebugOperationTargetPodApplyConfiguration) WithNamespace(value string) *KubectlDebugOperationTargetPodApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *KubectlDebugOperationTargetPodApplyConfiguration) WithName(value string) *KubectlDebugOperationTargetPodApplyConfiguration {
	b.Name = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *KubectlDebugOperationTargetPodApplyConfiguration) WithUID(value types.UID) *KubectlDebugOperationTargetPodApplyConfiguration {
	b.UID = &value
	return b
}
