/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// KubectlDebugTargetNamespaceConstraintsApplyConfiguration represents a declarative configuration of the KubectlDebugTargetNamespaceConstraints type for use
// with apply.
//
// KubectlDebugTargetNamespaceConstraints narrows the source namespaces
// accessible to kubectl-debug operations through a binding.
type KubectlDebugTargetNamespaceConstraintsApplyConfiguration struct {
	// ephemeralContainers is an additional allowlist for ephemeral-container
	// targets. It is intersected with the template's allowed namespaces.
	EphemeralContainers *NamespaceFilterApplyConfiguration `json:"ephemeralContainers,omitempty"`
	// podCopy is an additional allowlist for pod-copy source namespaces.
	// It is intersected with the template's allowed namespaces.
	PodCopy *NamespaceFilterApplyConfiguration `json:"podCopy,omitempty"`
}

// KubectlDebugTargetNamespaceConstraintsApplyConfiguration constructs a declarative configuration of the KubectlDebugTargetNamespaceConstraints type for use with
// apply.
func KubectlDebugTargetNamespaceConstraints() *KubectlDebugTargetNamespaceConstraintsApplyConfiguration {
	return &KubectlDebugTargetNamespaceConstraintsApplyConfiguration{}
}

// WithEphemeralContainers sets the EphemeralContainers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EphemeralContainers field is set to the value of the last call.
func (b *KubectlDebugTargetNamespaceConstraintsApplyConfiguration) WithEphemeralContainers(value *NamespaceFilterApplyConfiguration) *KubectlDebugTargetNamespaceConstraintsApplyConfiguration {
	b.EphemeralContainers = value
	return b
}

// WithPodCopy sets the PodCopy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodCopy field is set to the value of the last call.
func (b *KubectlDebugTargetNamespaceConstraintsApplyConfiguration) WithPodCopy(value *NamespaceFilterApplyConfiguration) *KubectlDebugTargetNamespaceConstraintsApplyConfiguration {
	b.PodCopy = value
	return b
}
