/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// KubectlDebugStatusApplyConfiguration represents a declarative configuration of the KubectlDebugStatus type for use
// with apply.
//
// KubectlDebugStatus tracks kubectl debug operations.
type KubectlDebugStatusApplyConfiguration struct {
	// ephemeralContainersInjected lists injected ephemeral containers.
	EphemeralContainersInjected []EphemeralContainerRefApplyConfiguration `json:"ephemeralContainersInjected,omitempty"`
	// copiedPods lists debug copies of pods.
	CopiedPods []CopiedPodRefApplyConfiguration `json:"copiedPods,omitempty"`
}

// KubectlDebugStatusApplyConfiguration constructs a declarative configuration of the KubectlDebugStatus type for use with
// apply.
func KubectlDebugStatus() *KubectlDebugStatusApplyConfiguration {
	return &KubectlDebugStatusApplyConfiguration{}
}

// WithEphemeralContainersInjected adds the given value to the EphemeralContainersInjected field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the EphemeralContainersInjected field.
func (b *KubectlDebugStatusApplyConfiguration) WithEphemeralContainersInjected(values ...*EphemeralContainerRefApplyConfiguration) *KubectlDebugStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEphemeralContainersInjected")
		}
		b.EphemeralContainersInjected = append(b.EphemeralContainersInjected, *values[i])
	}
	return b
}

// WithCopiedPods adds the given value to the CopiedPods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CopiedPods field.
func (b *KubectlDebugStatusApplyConfiguration) WithCopiedPods(values ...*CopiedPodRefApplyConfiguration) *KubectlDebugStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCopiedPods")
		}
		b.CopiedPods = append(b.CopiedPods, *values[i])
	}
	return b
}
