/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// LogSinkSpecApplyConfiguration represents a declarative configuration of the LogSinkSpec type for use
// with apply.
//
// LogSinkSpec configures the log audit sink.
type LogSinkSpecApplyConfiguration struct {
	// Level sets the log level for audit events.
	Level *string `json:"level,omitempty"`
	// Format sets the log format.
	Format *string `json:"format,omitempty"`
}

// LogSinkSpecApplyConfiguration constructs a declarative configuration of the LogSinkSpec type for use with
// apply.
func LogSinkSpec() *LogSinkSpecApplyConfiguration {
	return &LogSinkSpecApplyConfiguration{}
}

// WithLevel sets the Level field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Level field is set to the value of the last call.
func (b *LogSinkSpecApplyConfiguration) WithLevel(value string) *LogSinkSpecApplyConfiguration {
	b.Level = &value
	return b
}

// WithFormat sets the Format field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Format field is set to the value of the last call.
func (b *LogSinkSpecApplyConfiguration) WithFormat(value string) *LogSinkSpecApplyConfiguration {
	b.Format = &value
	return b
}
