/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MailProviderSpecApplyConfiguration represents a declarative configuration of the MailProviderSpec type for use
// with apply.
//
// MailProviderSpec defines the desired state of MailProvider
type MailProviderSpecApplyConfiguration struct {
	// DisplayName is a human-readable name for this mail provider
	DisplayName *string `json:"displayName,omitempty"`
	// Default indicates this is the default mail provider when no specific provider is selected
	// Only one MailProvider should have Default=true
	Default *bool `json:"default,omitempty"`
	// Disabled allows temporarily disabling a mail provider without deleting it
	// When disabled, emails will not be sent through this provider
	Disabled *bool `json:"disabled,omitempty"`
	// SMTP contains SMTP server configuration
	SMTP *SMTPConfigApplyConfiguration `json:"smtp,omitempty"`
	// Sender contains email sender configuration
	Sender *SenderConfigApplyConfiguration `json:"sender,omitempty"`
	// Retry contains retry and queue configuration
	Retry *RetryConfigApplyConfiguration `json:"retry,omitempty"`
}

// MailProviderSpecApplyConfiguration constructs a declarative configuration of the MailProviderSpec type for use with
// apply.
func MailProviderSpec() *MailProviderSpecApplyConfiguration {
	return &MailProviderSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *MailProviderSpecApplyConfiguration) WithDisplayName(value string) *MailProviderSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *MailProviderSpecApplyConfiguration) WithDefault(value bool) *MailProviderSpecApplyConfiguration {
	b.Default = &value
	return b
}

// WithDisabled sets the Disabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disabled field is set to the value of the last call.
func (b *MailProviderSpecApplyConfiguration) WithDisabled(value bool) *MailProviderSpecApplyConfiguration {
	b.Disabled = &value
	return b
}

// WithSMTP sets the SMTP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SMTP field is set to the value of the last call.
func (b *MailProviderSpecApplyConfiguration) WithSMTP(value *SMTPConfigApplyConfiguration) *MailProviderSpecApplyConfiguration {
	b.SMTP = value
	return b
}

// WithSender sets the Sender field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sender field is set to the value of the last call.
func (b *MailProviderSpecApplyConfiguration) WithSender(value *SenderConfigApplyConfiguration) *MailProviderSpecApplyConfiguration {
	b.Sender = value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *MailProviderSpecApplyConfiguration) WithRetry(value *RetryConfigApplyConfiguration) *MailProviderSpecApplyConfiguration {
	b.Retry = value
	return b
}
