/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MailProviderStatusApplyConfiguration represents a declarative configuration of the MailProviderStatus type for use
// with apply.
//
// MailProviderStatus defines the observed state of MailProvider
type MailProviderStatusApplyConfiguration struct {
	// ObservedGeneration reflects the generation of the most recently observed MailProvider.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of the MailProvider's state
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// LastHealthCheck is the timestamp of the last successful health check
	LastHealthCheck *metav1.Time `json:"lastHealthCheck,omitempty"`
	// LastSendAttempt is the timestamp of the last email send attempt
	LastSendAttempt *metav1.Time `json:"lastSendAttempt,omitempty"`
	// LastSendError contains the error message from the last failed send attempt
	LastSendError *string `json:"lastSendError,omitempty"`
}

// MailProviderStatusApplyConfiguration constructs a declarative configuration of the MailProviderStatus type for use with
// apply.
func MailProviderStatus() *MailProviderStatusApplyConfiguration {
	return &MailProviderStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MailProviderStatusApplyConfiguration) WithObservedGeneration(value int64) *MailProviderStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *MailProviderStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *MailProviderStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithLastHealthCheck sets the LastHealthCheck field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastHealthCheck field is set to the value of the last call.
func (b *MailProviderStatusApplyConfiguration) WithLastHealthCheck(value metav1.Time) *MailProviderStatusApplyConfiguration {
	b.LastHealthCheck = &value
	return b
}

// WithLastSendAttempt sets the LastSendAttempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSendAttempt field is set to the value of the last call.
func (b *MailProviderStatusApplyConfiguration) WithLastSendAttempt(value metav1.Time) *MailProviderStatusApplyConfiguration {
	b.LastSendAttempt = &value
	return b
}

// WithLastSendError sets the LastSendError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSendError field is set to the value of the last call.
func (b *MailProviderStatusApplyConfiguration) WithLastSendError(value string) *MailProviderStatusApplyConfiguration {
	b.LastSendError = &value
	return b
}
