/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NamespaceConstraintsApplyConfiguration represents a declarative configuration of the NamespaceConstraints type for use
// with apply.
//
// NamespaceConstraints defines where debug pods can be deployed.
// This allows user choice within administrator-defined boundaries.
type NamespaceConstraintsApplyConfiguration struct {
	// allowedNamespaces specifies namespaces where debug pods can be deployed.
	// Uses NamespaceFilter for pattern and label-based selection.
	// If empty, only defaultNamespace is allowed.
	AllowedNamespaces *NamespaceFilterApplyConfiguration `json:"allowedNamespaces,omitempty"`
	// deniedNamespaces specifies namespaces that are never allowed.
	// Evaluated AFTER allowedNamespaces (deny takes precedence).
	DeniedNamespaces *NamespaceFilterApplyConfiguration `json:"deniedNamespaces,omitempty"`
	// defaultNamespace is used when user doesn't specify a namespace.
	// Must be within allowedNamespaces if specified.
	DefaultNamespace *string `json:"defaultNamespace,omitempty"`
	// allowUserNamespace allows users to request a specific namespace.
	// If false, only defaultNamespace is used.
	AllowUserNamespace *bool `json:"allowUserNamespace,omitempty"`
	// createIfNotExists creates the target namespace if it doesn't exist.
	// Requires appropriate RBAC permissions.
	CreateIfNotExists *bool `json:"createIfNotExists,omitempty"`
	// namespaceLabels are labels applied to created namespaces.
	// Only used when createIfNotExists=true.
	NamespaceLabels map[string]string `json:"namespaceLabels,omitempty"`
}

// NamespaceConstraintsApplyConfiguration constructs a declarative configuration of the NamespaceConstraints type for use with
// apply.
func NamespaceConstraints() *NamespaceConstraintsApplyConfiguration {
	return &NamespaceConstraintsApplyConfiguration{}
}

// WithAllowedNamespaces sets the AllowedNamespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedNamespaces field is set to the value of the last call.
func (b *NamespaceConstraintsApplyConfiguration) WithAllowedNamespaces(value *NamespaceFilterApplyConfiguration) *NamespaceConstraintsApplyConfiguration {
	b.AllowedNamespaces = value
	return b
}

// WithDeniedNamespaces sets the DeniedNamespaces field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeniedNamespaces field is set to the value of the last call.
func (b *NamespaceConstraintsApplyConfiguration) WithDeniedNamespaces(value *NamespaceFilterApplyConfiguration) *NamespaceConstraintsApplyConfiguration {
	b.DeniedNamespaces = value
	return b
}

// WithDefaultNamespace sets the DefaultNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultNamespace field is set to the value of the last call.
func (b *NamespaceConstraintsApplyConfiguration) WithDefaultNamespace(value string) *NamespaceConstraintsApplyConfiguration {
	b.DefaultNamespace = &value
	return b
}

// WithAllowUserNamespace sets the AllowUserNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowUserNamespace field is set to the value of the last call.
func (b *NamespaceConstraintsApplyConfiguration) WithAllowUserNamespace(value bool) *NamespaceConstraintsApplyConfiguration {
	b.AllowUserNamespace = &value
	return b
}

// WithCreateIfNotExists sets the CreateIfNotExists field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateIfNotExists field is set to the value of the last call.
func (b *NamespaceConstraintsApplyConfiguration) WithCreateIfNotExists(value bool) *NamespaceConstraintsApplyConfiguration {
	b.CreateIfNotExists = &value
	return b
}

// WithNamespaceLabels puts the entries into the NamespaceLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NamespaceLabels field,
// overwriting an existing map entries in NamespaceLabels field with the same key.
func (b *NamespaceConstraintsApplyConfiguration) WithNamespaceLabels(entries map[string]string) *NamespaceConstraintsApplyConfiguration {
	if b.NamespaceLabels == nil && len(entries) > 0 {
		b.NamespaceLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NamespaceLabels[k] = v
	}
	return b
}
