/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	breakglassv1alpha1 "github.com/telekom/k8s-breakglass/api/v1alpha1"
)

// NamespaceSelectorRequirementApplyConfiguration represents a declarative configuration of the NamespaceSelectorRequirement type for use
// with apply.
//
// NamespaceSelectorRequirement is a selector requirement for namespaces.
// Mirrors metav1.LabelSelectorRequirement for consistency with Kubernetes patterns.
type NamespaceSelectorRequirementApplyConfiguration struct {
	// key is the label key the selector applies to.
	Key *string `json:"key,omitempty"`
	// operator represents a key's relationship to a set of values.
	// Valid operators: In, NotIn, Exists, DoesNotExist.
	Operator *breakglassv1alpha1.NamespaceSelectorOperator `json:"operator,omitempty"`
	// values is an array of string values.
	// Required for In and NotIn operators.
	// Must be empty for Exists and DoesNotExist.
	Values []string `json:"values,omitempty"`
}

// NamespaceSelectorRequirementApplyConfiguration constructs a declarative configuration of the NamespaceSelectorRequirement type for use with
// apply.
func NamespaceSelectorRequirement() *NamespaceSelectorRequirementApplyConfiguration {
	return &NamespaceSelectorRequirementApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *NamespaceSelectorRequirementApplyConfiguration) WithKey(value string) *NamespaceSelectorRequirementApplyConfiguration {
	b.Key = &value
	return b
}

// WithOperator sets the Operator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Operator field is set to the value of the last call.
func (b *NamespaceSelectorRequirementApplyConfiguration) WithOperator(value breakglassv1alpha1.NamespaceSelectorOperator) *NamespaceSelectorRequirementApplyConfiguration {
	b.Operator = &value
	return b
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *NamespaceSelectorRequirementApplyConfiguration) WithValues(values ...string) *NamespaceSelectorRequirementApplyConfiguration {
	for i := range values {
		b.Values = append(b.Values, values[i])
	}
	return b
}
