/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// NotificationExclusionsApplyConfiguration represents a declarative configuration of the NotificationExclusions type for use
// with apply.
//
// NotificationExclusions defines which users/groups should be excluded from email notifications
type NotificationExclusionsApplyConfiguration struct {
	// users is a list of user emails/usernames to exclude from notifications
	Users []string `json:"users,omitempty"`
	// groups is a list of approver groups to exclude from notifications
	Groups []string `json:"groups,omitempty"`
}

// NotificationExclusionsApplyConfiguration constructs a declarative configuration of the NotificationExclusions type for use with
// apply.
func NotificationExclusions() *NotificationExclusionsApplyConfiguration {
	return &NotificationExclusionsApplyConfiguration{}
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *NotificationExclusionsApplyConfiguration) WithUsers(values ...string) *NotificationExclusionsApplyConfiguration {
	for i := range values {
		b.Users = append(b.Users, values[i])
	}
	return b
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *NotificationExclusionsApplyConfiguration) WithGroups(values ...string) *NotificationExclusionsApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}
