/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PodSecurityRulesApplyConfiguration represents a declarative configuration of the PodSecurityRules type for use
// with apply.
//
// PodSecurityRules defines risk-based evaluation for pod exec/attach/portforward operations.
// When users attempt to exec into pods, these rules evaluate the pod's security posture
// and can deny access to high-risk pods (e.g., privileged, hostNetwork, hostPath).
type PodSecurityRulesApplyConfiguration struct {
	// appliesTo specifies which pod subresources trigger this evaluation.
	// Default: exec, attach, portforward
	AppliesTo *PodSecurityScopeApplyConfiguration `json:"appliesTo,omitempty"`
	// riskFactors assigns numeric weights (0-100) to dangerous pod configurations.
	// The total risk score is the sum of all detected factors.
	RiskFactors *RiskFactorsApplyConfiguration `json:"riskFactors,omitempty"`
	// thresholds define actions based on cumulative risk score.
	// Evaluated in order; first matching threshold determines the action.
	Thresholds []RiskThresholdApplyConfiguration `json:"thresholds,omitempty"`
	// blockFactors immediately deny if ANY listed factor is present, regardless of score.
	// Valid values: hostNetwork, hostPID, hostIPC, privilegedContainer, hostPathWritable, runAsRoot
	BlockFactors []string `json:"blockFactors,omitempty"`
	// exemptions exclude certain pods from security evaluation.
	Exemptions *PodSecurityExemptionsApplyConfiguration `json:"exemptions,omitempty"`
	// failMode determines behavior when pod spec cannot be fetched from target cluster.
	// "open" = allow request if fetch fails (fail-open)
	// "closed" = deny request if fetch fails (fail-closed, more secure)
	FailMode *string `json:"failMode,omitempty"`
}

// PodSecurityRulesApplyConfiguration constructs a declarative configuration of the PodSecurityRules type for use with
// apply.
func PodSecurityRules() *PodSecurityRulesApplyConfiguration {
	return &PodSecurityRulesApplyConfiguration{}
}

// WithAppliesTo sets the AppliesTo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppliesTo field is set to the value of the last call.
func (b *PodSecurityRulesApplyConfiguration) WithAppliesTo(value *PodSecurityScopeApplyConfiguration) *PodSecurityRulesApplyConfiguration {
	b.AppliesTo = value
	return b
}

// WithRiskFactors sets the RiskFactors field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RiskFactors field is set to the value of the last call.
func (b *PodSecurityRulesApplyConfiguration) WithRiskFactors(value *RiskFactorsApplyConfiguration) *PodSecurityRulesApplyConfiguration {
	b.RiskFactors = value
	return b
}

// WithThresholds adds the given value to the Thresholds field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Thresholds field.
func (b *PodSecurityRulesApplyConfiguration) WithThresholds(values ...*RiskThresholdApplyConfiguration) *PodSecurityRulesApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithThresholds")
		}
		b.Thresholds = append(b.Thresholds, *values[i])
	}
	return b
}

// WithBlockFactors adds the given value to the BlockFactors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BlockFactors field.
func (b *PodSecurityRulesApplyConfiguration) WithBlockFactors(values ...string) *PodSecurityRulesApplyConfiguration {
	for i := range values {
		b.BlockFactors = append(b.BlockFactors, values[i])
	}
	return b
}

// WithExemptions sets the Exemptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exemptions field is set to the value of the last call.
func (b *PodSecurityRulesApplyConfiguration) WithExemptions(value *PodSecurityExemptionsApplyConfiguration) *PodSecurityRulesApplyConfiguration {
	b.Exemptions = value
	return b
}

// WithFailMode sets the FailMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailMode field is set to the value of the last call.
func (b *PodSecurityRulesApplyConfiguration) WithFailMode(value string) *PodSecurityRulesApplyConfiguration {
	b.FailMode = &value
	return b
}
