/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PodSecurityOverridesApplyConfiguration represents a declarative configuration of the PodSecurityOverrides type for use
// with apply.
//
// PodSecurityOverrides defines how an escalation can relax pod security rules.
// These overrides apply when evaluating DenyPolicy.podSecurityRules for users with this escalation.
type PodSecurityOverridesApplyConfiguration struct {
	// enabled activates pod security overrides for this escalation.
	// If false, no overrides are applied regardless of other settings.
	Enabled *bool `json:"enabled,omitempty"`
	// maxAllowedScore overrides the risk score threshold for this escalation.
	// If set, pods with risk scores up to this value will be allowed (instead of the DenyPolicy threshold).
	// Example: Set to 150 to allow exec to privileged pods for senior SREs.
	MaxAllowedScore *int `json:"maxAllowedScore,omitempty"`
	// exemptFactors lists risk factors that should NOT block access for this escalation.
	// These factors are skipped during pod security evaluation for users with this escalation.
	// Valid values: hostNetwork, hostPID, hostIPC, privilegedContainer, hostPathWritable, hostPathReadOnly, runAsRoot
	// Example: ["privilegedContainer", "hostNetwork"] allows exec to privileged/hostNetwork pods.
	ExemptFactors []string `json:"exemptFactors,omitempty"`
	// namespaceScope limits where overrides apply. If set, overrides only work for pods in these namespaces.
	// If empty, overrides apply to all namespaces (subject to DenyPolicy scope).
	// Supports pattern matching (glob-style) and label-based namespace selection.
	NamespaceScope *NamespaceFilterApplyConfiguration `json:"namespaceScope,omitempty"`
	// requireApproval requires additional approval before overrides can be used.
	// When true, the session must be approved by someone in the approvers list.
	// This adds an extra check beyond the normal escalation approval.
	RequireApproval *bool `json:"requireApproval,omitempty"`
	// approvers defines who can approve the use of pod security overrides.
	// Only used when requireApproval is true.
	Approvers *PodSecurityApproversApplyConfiguration `json:"approvers,omitempty"`
}

// PodSecurityOverridesApplyConfiguration constructs a declarative configuration of the PodSecurityOverrides type for use with
// apply.
func PodSecurityOverrides() *PodSecurityOverridesApplyConfiguration {
	return &PodSecurityOverridesApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *PodSecurityOverridesApplyConfiguration) WithEnabled(value bool) *PodSecurityOverridesApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithMaxAllowedScore sets the MaxAllowedScore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAllowedScore field is set to the value of the last call.
func (b *PodSecurityOverridesApplyConfiguration) WithMaxAllowedScore(value int) *PodSecurityOverridesApplyConfiguration {
	b.MaxAllowedScore = &value
	return b
}

// WithExemptFactors adds the given value to the ExemptFactors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExemptFactors field.
func (b *PodSecurityOverridesApplyConfiguration) WithExemptFactors(values ...string) *PodSecurityOverridesApplyConfiguration {
	for i := range values {
		b.ExemptFactors = append(b.ExemptFactors, values[i])
	}
	return b
}

// WithNamespaceScope sets the NamespaceScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceScope field is set to the value of the last call.
func (b *PodSecurityOverridesApplyConfiguration) WithNamespaceScope(value *NamespaceFilterApplyConfiguration) *PodSecurityOverridesApplyConfiguration {
	b.NamespaceScope = value
	return b
}

// WithRequireApproval sets the RequireApproval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireApproval field is set to the value of the last call.
func (b *PodSecurityOverridesApplyConfiguration) WithRequireApproval(value bool) *PodSecurityOverridesApplyConfiguration {
	b.RequireApproval = &value
	return b
}

// WithApprovers sets the Approvers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Approvers field is set to the value of the last call.
func (b *PodSecurityOverridesApplyConfiguration) WithApprovers(value *PodSecurityApproversApplyConfiguration) *PodSecurityOverridesApplyConfiguration {
	b.Approvers = value
	return b
}
