/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PodSecurityApproversApplyConfiguration represents a declarative configuration of the PodSecurityApprovers type for use
// with apply.
//
// PodSecurityApprovers defines who can approve pod security override usage.
type PodSecurityApproversApplyConfiguration struct {
	// groups that can approve pod security override usage
	Groups []string `json:"groups,omitempty"`
	// users that can approve pod security override usage
	Users []string `json:"users,omitempty"`
}

// PodSecurityApproversApplyConfiguration constructs a declarative configuration of the PodSecurityApprovers type for use with
// apply.
func PodSecurityApprovers() *PodSecurityApproversApplyConfiguration {
	return &PodSecurityApproversApplyConfiguration{}
}

// WithGroups adds the given value to the Groups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Groups field.
func (b *PodSecurityApproversApplyConfiguration) WithGroups(values ...string) *PodSecurityApproversApplyConfiguration {
	for i := range values {
		b.Groups = append(b.Groups, values[i])
	}
	return b
}

// WithUsers adds the given value to the Users field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Users field.
func (b *PodSecurityApproversApplyConfiguration) WithUsers(values ...string) *PodSecurityApproversApplyConfiguration {
	for i := range values {
		b.Users = append(b.Users, values[i])
	}
	return b
}
