/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PodTemplateResourceStatusApplyConfiguration represents a declarative configuration of the PodTemplateResourceStatus type for use
// with apply.
//
// PodTemplateResourceStatus tracks the state of resources deployed from multi-doc pod templates.
type PodTemplateResourceStatusApplyConfiguration struct {
	// kind is the Kubernetes kind of the resource.
	Kind *string `json:"kind,omitempty"`
	// apiVersion is the API version of the resource.
	APIVersion *string `json:"apiVersion,omitempty"`
	// resourceName is the name of the deployed resource.
	ResourceName *string `json:"resourceName,omitempty"`
	// namespace is the namespace where the resource is deployed.
	Namespace *string `json:"namespace,omitempty"`
	// source identifies where this resource came from.
	// Either "podTemplateString" or "debugPodTemplate:<name>".
	Source *string `json:"source,omitempty"`
	// created indicates whether the resource was successfully created.
	Created *bool `json:"created,omitempty"`
	// createdAt is when the resource was created.
	CreatedAt *string `json:"createdAt,omitempty"`
	// ready indicates whether the resource is ready (using kstatus).
	Ready *bool `json:"ready,omitempty"`
	// readyAt is when the resource became ready.
	ReadyAt *string `json:"readyAt,omitempty"`
	// readinessStatus provides the kstatus readiness state.
	ReadinessStatus *string `json:"readinessStatus,omitempty"`
	// deleted indicates whether the resource has been deleted.
	Deleted *bool `json:"deleted,omitempty"`
	// deletedAt is when the resource was deleted.
	DeletedAt *string `json:"deletedAt,omitempty"`
	// error contains any error message from resource operations.
	Error *string `json:"error,omitempty"`
}

// PodTemplateResourceStatusApplyConfiguration constructs a declarative configuration of the PodTemplateResourceStatus type for use with
// apply.
func PodTemplateResourceStatus() *PodTemplateResourceStatusApplyConfiguration {
	return &PodTemplateResourceStatusApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithKind(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithAPIVersion(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.APIVersion = &value
	return b
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithResourceName(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.ResourceName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithNamespace(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithSource(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.Source = &value
	return b
}

// WithCreated sets the Created field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Created field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithCreated(value bool) *PodTemplateResourceStatusApplyConfiguration {
	b.Created = &value
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithCreatedAt(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithReady(value bool) *PodTemplateResourceStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithReadyAt sets the ReadyAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyAt field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithReadyAt(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.ReadyAt = &value
	return b
}

// WithReadinessStatus sets the ReadinessStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadinessStatus field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithReadinessStatus(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.ReadinessStatus = &value
	return b
}

// WithDeleted sets the Deleted field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deleted field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithDeleted(value bool) *PodTemplateResourceStatusApplyConfiguration {
	b.Deleted = &value
	return b
}

// WithDeletedAt sets the DeletedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletedAt field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithDeletedAt(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.DeletedAt = &value
	return b
}

// WithError sets the Error field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Error field is set to the value of the last call.
func (b *PodTemplateResourceStatusApplyConfiguration) WithError(value string) *PodTemplateResourceStatusApplyConfiguration {
	b.Error = &value
	return b
}
