/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ReasonConfigApplyConfiguration represents a declarative configuration of the ReasonConfig type for use
// with apply.
type ReasonConfigApplyConfiguration struct {
	// mandatory indicates whether the field is required (true) or optional (false).
	Mandatory *bool `json:"mandatory,omitempty"`
	// description describes what to enter in the reason field (e.g. "CASM TicketID").
	Description *string `json:"description,omitempty"`
}

// ReasonConfigApplyConfiguration constructs a declarative configuration of the ReasonConfig type for use with
// apply.
func ReasonConfig() *ReasonConfigApplyConfiguration {
	return &ReasonConfigApplyConfiguration{}
}

// WithMandatory sets the Mandatory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mandatory field is set to the value of the last call.
func (b *ReasonConfigApplyConfiguration) WithMandatory(value bool) *ReasonConfigApplyConfiguration {
	b.Mandatory = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ReasonConfigApplyConfiguration) WithDescription(value string) *ReasonConfigApplyConfiguration {
	b.Description = &value
	return b
}
