/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ResolvedTemplateRefApplyConfiguration represents a declarative configuration of the ResolvedTemplateRef type for use
// with apply.
//
// ResolvedTemplateRef contains information about a resolved template.
type ResolvedTemplateRefApplyConfiguration struct {
	// name is the template name.
	Name *string `json:"name,omitempty"`
	// displayName is the effective display name (may include prefix from binding).
	DisplayName *string `json:"displayName,omitempty"`
	// ready indicates if the template is ready for use.
	Ready *bool `json:"ready,omitempty"`
}

// ResolvedTemplateRefApplyConfiguration constructs a declarative configuration of the ResolvedTemplateRef type for use with
// apply.
func ResolvedTemplateRef() *ResolvedTemplateRefApplyConfiguration {
	return &ResolvedTemplateRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResolvedTemplateRefApplyConfiguration) WithName(value string) *ResolvedTemplateRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ResolvedTemplateRefApplyConfiguration) WithDisplayName(value string) *ResolvedTemplateRefApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *ResolvedTemplateRefApplyConfiguration) WithReady(value bool) *ResolvedTemplateRefApplyConfiguration {
	b.Ready = &value
	return b
}
