/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ResolvedClusterRefApplyConfiguration represents a declarative configuration of the ResolvedClusterRef type for use
// with apply.
//
// ResolvedClusterRef contains information about a resolved cluster.
type ResolvedClusterRefApplyConfiguration struct {
	// name is the cluster name (from ClusterConfig).
	Name *string `json:"name,omitempty"`
	// ready indicates if the cluster is ready/reachable.
	Ready *bool `json:"ready,omitempty"`
	// matchedBy indicates how this cluster was matched ("explicit" or "selector").
	MatchedBy *string `json:"matchedBy,omitempty"`
}

// ResolvedClusterRefApplyConfiguration constructs a declarative configuration of the ResolvedClusterRef type for use with
// apply.
func ResolvedClusterRef() *ResolvedClusterRefApplyConfiguration {
	return &ResolvedClusterRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResolvedClusterRefApplyConfiguration) WithName(value string) *ResolvedClusterRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *ResolvedClusterRefApplyConfiguration) WithReady(value bool) *ResolvedClusterRefApplyConfiguration {
	b.Ready = &value
	return b
}

// WithMatchedBy sets the MatchedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchedBy field is set to the value of the last call.
func (b *ResolvedClusterRefApplyConfiguration) WithMatchedBy(value string) *ResolvedClusterRefApplyConfiguration {
	b.MatchedBy = &value
	return b
}
