/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RetryConfigApplyConfiguration represents a declarative configuration of the RetryConfig type for use
// with apply.
//
// RetryConfig defines retry and queue behavior
type RetryConfigApplyConfiguration struct {
	// Count is the number of retry attempts after initial send fails
	// Default: 3
	Count *int `json:"count,omitempty"`
	// InitialBackoffMs is the initial backoff duration in milliseconds for exponential backoff
	// Subsequent retries double the backoff time
	// Default: 100ms
	InitialBackoffMs *int `json:"initialBackoffMs,omitempty"`
	// QueueSize is the maximum number of pending emails in the queue
	// Default: 1000
	QueueSize *int `json:"queueSize,omitempty"`
}

// RetryConfigApplyConfiguration constructs a declarative configuration of the RetryConfig type for use with
// apply.
func RetryConfig() *RetryConfigApplyConfiguration {
	return &RetryConfigApplyConfiguration{}
}

// WithCount sets the Count field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Count field is set to the value of the last call.
func (b *RetryConfigApplyConfiguration) WithCount(value int) *RetryConfigApplyConfiguration {
	b.Count = &value
	return b
}

// WithInitialBackoffMs sets the InitialBackoffMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialBackoffMs field is set to the value of the last call.
func (b *RetryConfigApplyConfiguration) WithInitialBackoffMs(value int) *RetryConfigApplyConfiguration {
	b.InitialBackoffMs = &value
	return b
}

// WithQueueSize sets the QueueSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QueueSize field is set to the value of the last call.
func (b *RetryConfigApplyConfiguration) WithQueueSize(value int) *RetryConfigApplyConfiguration {
	b.QueueSize = &value
	return b
}
