/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RiskFactorsApplyConfiguration represents a declarative configuration of the RiskFactors type for use
// with apply.
//
// RiskFactors assigns numeric weights to various dangerous pod configurations.
// Each factor represents a security risk; higher values indicate greater risk.
// The total score is calculated by summing all detected factors.
type RiskFactorsApplyConfiguration struct {
	// hostNetwork: pod uses host network namespace (enables network sniffing, bypasses network policies)
	HostNetwork *int `json:"hostNetwork,omitempty"`
	// hostPID: pod uses host PID namespace (can see/signal all host processes)
	HostPID *int `json:"hostPID,omitempty"`
	// hostIPC: pod uses host IPC namespace (can access host shared memory)
	HostIPC *int `json:"hostIPC,omitempty"`
	// privilegedContainer: container runs in privileged mode (full host access)
	PrivilegedContainer *int `json:"privilegedContainer,omitempty"`
	// hostPathWritable: pod has writable hostPath volume mounts
	HostPathWritable *int `json:"hostPathWritable,omitempty"`
	// hostPathReadOnly: pod has read-only hostPath volume mounts (lower risk than writable)
	HostPathReadOnly *int `json:"hostPathReadOnly,omitempty"`
	// runAsRoot: container runs as root user (UID 0)
	RunAsRoot *int `json:"runAsRoot,omitempty"`
	// capabilities maps Linux capability names to risk scores.
	// Example: {"NET_ADMIN": 50, "SYS_ADMIN": 80, "SYS_PTRACE": 60}
	Capabilities map[string]int `json:"capabilities,omitempty"`
}

// RiskFactorsApplyConfiguration constructs a declarative configuration of the RiskFactors type for use with
// apply.
func RiskFactors() *RiskFactorsApplyConfiguration {
	return &RiskFactorsApplyConfiguration{}
}

// WithHostNetwork sets the HostNetwork field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostNetwork field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithHostNetwork(value int) *RiskFactorsApplyConfiguration {
	b.HostNetwork = &value
	return b
}

// WithHostPID sets the HostPID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPID field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithHostPID(value int) *RiskFactorsApplyConfiguration {
	b.HostPID = &value
	return b
}

// WithHostIPC sets the HostIPC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostIPC field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithHostIPC(value int) *RiskFactorsApplyConfiguration {
	b.HostIPC = &value
	return b
}

// WithPrivilegedContainer sets the PrivilegedContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivilegedContainer field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithPrivilegedContainer(value int) *RiskFactorsApplyConfiguration {
	b.PrivilegedContainer = &value
	return b
}

// WithHostPathWritable sets the HostPathWritable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPathWritable field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithHostPathWritable(value int) *RiskFactorsApplyConfiguration {
	b.HostPathWritable = &value
	return b
}

// WithHostPathReadOnly sets the HostPathReadOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPathReadOnly field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithHostPathReadOnly(value int) *RiskFactorsApplyConfiguration {
	b.HostPathReadOnly = &value
	return b
}

// WithRunAsRoot sets the RunAsRoot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunAsRoot field is set to the value of the last call.
func (b *RiskFactorsApplyConfiguration) WithRunAsRoot(value int) *RiskFactorsApplyConfiguration {
	b.RunAsRoot = &value
	return b
}

// WithCapabilities puts the entries into the Capabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Capabilities field,
// overwriting an existing map entries in Capabilities field with the same key.
func (b *RiskFactorsApplyConfiguration) WithCapabilities(entries map[string]int) *RiskFactorsApplyConfiguration {
	if b.Capabilities == nil && len(entries) > 0 {
		b.Capabilities = make(map[string]int, len(entries))
	}
	for k, v := range entries {
		b.Capabilities[k] = v
	}
	return b
}
