/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SchedulingOptionApplyConfiguration represents a declarative configuration of the SchedulingOption type for use
// with apply.
//
// SchedulingOption represents a single scheduling configuration choice.
type SchedulingOptionApplyConfiguration struct {
	// name is a unique identifier for this option (used in API requests).
	Name *string `json:"name,omitempty"`
	// displayName is the human-readable name shown in UI.
	DisplayName *string `json:"displayName,omitempty"`
	// description explains what this option does.
	Description *string `json:"description,omitempty"`
	// default marks this option as the pre-selected choice.
	// Only one option can be marked as default.
	Default *bool `json:"default,omitempty"`
	// schedulingConstraints are merged with the base constraints.
	// These are ADDITIVE - they cannot remove base constraints.
	SchedulingConstraints *SchedulingConstraintsApplyConfiguration `json:"schedulingConstraints,omitempty"`
	// allowedGroups restricts this option to specific groups.
	// If empty, all users with access to the template can use this option.
	AllowedGroups []string `json:"allowedGroups,omitempty"`
	// allowedUsers restricts this option to specific users.
	AllowedUsers []string `json:"allowedUsers,omitempty"`
}

// SchedulingOptionApplyConfiguration constructs a declarative configuration of the SchedulingOption type for use with
// apply.
func SchedulingOption() *SchedulingOptionApplyConfiguration {
	return &SchedulingOptionApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SchedulingOptionApplyConfiguration) WithName(value string) *SchedulingOptionApplyConfiguration {
	b.Name = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *SchedulingOptionApplyConfiguration) WithDisplayName(value string) *SchedulingOptionApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *SchedulingOptionApplyConfiguration) WithDescription(value string) *SchedulingOptionApplyConfiguration {
	b.Description = &value
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *SchedulingOptionApplyConfiguration) WithDefault(value bool) *SchedulingOptionApplyConfiguration {
	b.Default = &value
	return b
}

// WithSchedulingConstraints sets the SchedulingConstraints field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SchedulingConstraints field is set to the value of the last call.
func (b *SchedulingOptionApplyConfiguration) WithSchedulingConstraints(value *SchedulingConstraintsApplyConfiguration) *SchedulingOptionApplyConfiguration {
	b.SchedulingConstraints = value
	return b
}

// WithAllowedGroups adds the given value to the AllowedGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedGroups field.
func (b *SchedulingOptionApplyConfiguration) WithAllowedGroups(values ...string) *SchedulingOptionApplyConfiguration {
	for i := range values {
		b.AllowedGroups = append(b.AllowedGroups, values[i])
	}
	return b
}

// WithAllowedUsers adds the given value to the AllowedUsers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedUsers field.
func (b *SchedulingOptionApplyConfiguration) WithAllowedUsers(values ...string) *SchedulingOptionApplyConfiguration {
	for i := range values {
		b.AllowedUsers = append(b.AllowedUsers, values[i])
	}
	return b
}
