/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ServiceAccountTemplateApplyConfiguration represents a declarative configuration of the ServiceAccountTemplate type for use
// with apply.
//
// ServiceAccountTemplate defines how per-session ServiceAccounts are created.
type ServiceAccountTemplateApplyConfiguration struct {
	// namePrefix is prepended to the session name for the SA name.
	NamePrefix *string `json:"namePrefix,omitempty"`
	// labels to apply to created ServiceAccounts.
	Labels map[string]string `json:"labels,omitempty"`
	// annotations to apply to created ServiceAccounts.
	Annotations map[string]string `json:"annotations,omitempty"`
}

// ServiceAccountTemplateApplyConfiguration constructs a declarative configuration of the ServiceAccountTemplate type for use with
// apply.
func ServiceAccountTemplate() *ServiceAccountTemplateApplyConfiguration {
	return &ServiceAccountTemplateApplyConfiguration{}
}

// WithNamePrefix sets the NamePrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamePrefix field is set to the value of the last call.
func (b *ServiceAccountTemplateApplyConfiguration) WithNamePrefix(value string) *ServiceAccountTemplateApplyConfiguration {
	b.NamePrefix = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ServiceAccountTemplateApplyConfiguration) WithLabels(entries map[string]string) *ServiceAccountTemplateApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ServiceAccountTemplateApplyConfiguration) WithAnnotations(entries map[string]string) *ServiceAccountTemplateApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
