/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SMTPConfigApplyConfiguration represents a declarative configuration of the SMTPConfig type for use
// with apply.
//
// SMTPConfig defines SMTP server connection settings
type SMTPConfigApplyConfiguration struct {
	// Host is the SMTP server hostname
	// Example: smtp.gmail.com, smtp.example.com
	Host *string `json:"host,omitempty"`
	// Port is the SMTP server port
	// Common values: 587 (STARTTLS), 465 (TLS), 25 (plain)
	Port *int `json:"port,omitempty"`
	// Username for SMTP authentication
	Username *string `json:"username,omitempty"`
	// PasswordRef references a Secret containing the SMTP password
	PasswordRef *SecretKeyReferenceApplyConfiguration `json:"passwordRef,omitempty"`
	// InsecureSkipVerify allows skipping TLS certificate verification
	// WARNING: Only use for testing/development!
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
	// CertificateAuthority contains a PEM encoded CA certificate for TLS validation
	CertificateAuthority *string `json:"certificateAuthority,omitempty"`
	// DisableTLS disables TLS/STARTTLS encryption for the SMTP connection.
	// Use this when connecting to plain SMTP servers like MailHog that don't support TLS.
	// WARNING: Only use for testing/development environments!
	DisableTLS *bool `json:"disableTLS,omitempty"`
}

// SMTPConfigApplyConfiguration constructs a declarative configuration of the SMTPConfig type for use with
// apply.
func SMTPConfig() *SMTPConfigApplyConfiguration {
	return &SMTPConfigApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithHost(value string) *SMTPConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithPort(value int) *SMTPConfigApplyConfiguration {
	b.Port = &value
	return b
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithUsername(value string) *SMTPConfigApplyConfiguration {
	b.Username = &value
	return b
}

// WithPasswordRef sets the PasswordRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PasswordRef field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithPasswordRef(value *SecretKeyReferenceApplyConfiguration) *SMTPConfigApplyConfiguration {
	b.PasswordRef = value
	return b
}

// WithInsecureSkipVerify sets the InsecureSkipVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureSkipVerify field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithInsecureSkipVerify(value bool) *SMTPConfigApplyConfiguration {
	b.InsecureSkipVerify = &value
	return b
}

// WithCertificateAuthority sets the CertificateAuthority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CertificateAuthority field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithCertificateAuthority(value string) *SMTPConfigApplyConfiguration {
	b.CertificateAuthority = &value
	return b
}

// WithDisableTLS sets the DisableTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisableTLS field is set to the value of the last call.
func (b *SMTPConfigApplyConfiguration) WithDisableTLS(value bool) *SMTPConfigApplyConfiguration {
	b.DisableTLS = &value
	return b
}
