/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TemplateReferenceApplyConfiguration represents a declarative configuration of the TemplateReference type for use
// with apply.
//
// TemplateReference references a DebugSessionTemplate by name.
type TemplateReferenceApplyConfiguration struct {
	// name is the name of the DebugSessionTemplate.
	Name *string `json:"name,omitempty"`
}

// TemplateReferenceApplyConfiguration constructs a declarative configuration of the TemplateReference type for use with
// apply.
func TemplateReference() *TemplateReferenceApplyConfiguration {
	return &TemplateReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TemplateReferenceApplyConfiguration) WithName(value string) *TemplateReferenceApplyConfiguration {
	b.Name = &value
	return b
}
