/*
SPDX-FileCopyrightText: 2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

type TerminalRecordingArtifactApplyConfiguration struct {
	URI       *string  `json:"uri,omitempty"`
	SHA256    *string  `json:"sha256,omitempty"`
	SizeBytes *int64   `json:"sizeBytes,omitempty"`
	ExpiresAt *v1.Time `json:"expiresAt,omitempty"`
	ReplayURL *string  `json:"replayUrl,omitempty"`
}

func TerminalRecordingArtifact() *TerminalRecordingArtifactApplyConfiguration {
	return &TerminalRecordingArtifactApplyConfiguration{}
}

func (b *TerminalRecordingArtifactApplyConfiguration) WithURI(value string) *TerminalRecordingArtifactApplyConfiguration {
	b.URI = &value
	return b
}

func (b *TerminalRecordingArtifactApplyConfiguration) WithSHA256(value string) *TerminalRecordingArtifactApplyConfiguration {
	b.SHA256 = &value
	return b
}

func (b *TerminalRecordingArtifactApplyConfiguration) WithSizeBytes(value int64) *TerminalRecordingArtifactApplyConfiguration {
	b.SizeBytes = &value
	return b
}

func (b *TerminalRecordingArtifactApplyConfiguration) WithExpiresAt(value v1.Time) *TerminalRecordingArtifactApplyConfiguration {
	b.ExpiresAt = &value
	return b
}

func (b *TerminalRecordingArtifactApplyConfiguration) WithReplayURL(value string) *TerminalRecordingArtifactApplyConfiguration {
	b.ReplayURL = &value
	return b
}
