/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TerminalSharingStatusApplyConfiguration represents a declarative configuration of the TerminalSharingStatus type for use
// with apply.
//
// TerminalSharingStatus contains terminal sharing information.
type TerminalSharingStatusApplyConfiguration struct {
	// enabled indicates if terminal sharing is active.
	Enabled *bool `json:"enabled,omitempty"`
	// sessionName is the tmux/screen session name.
	SessionName *string `json:"sessionName,omitempty"`
	// attachCommand is the command to attach to the shared terminal.
	AttachCommand *string `json:"attachCommand,omitempty"`
}

// TerminalSharingStatusApplyConfiguration constructs a declarative configuration of the TerminalSharingStatus type for use with
// apply.
func TerminalSharingStatus() *TerminalSharingStatusApplyConfiguration {
	return &TerminalSharingStatusApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *TerminalSharingStatusApplyConfiguration) WithEnabled(value bool) *TerminalSharingStatusApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithSessionName sets the SessionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionName field is set to the value of the last call.
func (b *TerminalSharingStatusApplyConfiguration) WithSessionName(value string) *TerminalSharingStatusApplyConfiguration {
	b.SessionName = &value
	return b
}

// WithAttachCommand sets the AttachCommand field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AttachCommand field is set to the value of the last call.
func (b *TerminalSharingStatusApplyConfiguration) WithAttachCommand(value string) *TerminalSharingStatusApplyConfiguration {
	b.AttachCommand = &value
	return b
}
