/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TokenExchangeConfigApplyConfiguration represents a declarative configuration of the TokenExchangeConfig type for use
// with apply.
//
// TokenExchangeConfig configures OAuth 2.0 token exchange (RFC 8693).
// Token exchange allows the controller to exchange a subject token (stored in a secret)
// for a cluster-scoped access token. This is useful for scenarios where:
// - A service account token needs to be exchanged for a cluster-specific token
// - Cross-realm authentication is required
// - The OIDC provider supports token exchange for delegation
type TokenExchangeConfigApplyConfiguration struct {
	// enabled activates token exchange flow.
	Enabled *bool `json:"enabled,omitempty"`
	// subjectTokenSecretRef references a secret containing the subject token to exchange.
	// This is required when enabled=true. The controller reads this token and exchanges
	// it for a cluster-scoped token using RFC 8693 token exchange.
	SubjectTokenSecretRef *SecretKeyReferenceApplyConfiguration `json:"subjectTokenSecretRef,omitempty"`
	// subjectTokenType specifies the type of the subject token being exchanged.
	// Default: urn:ietf:params:oauth:token-type:access_token
	SubjectTokenType *string `json:"subjectTokenType,omitempty"`
	// requestedTokenType specifies the type of token to request.
	// Default: urn:ietf:params:oauth:token-type:access_token
	RequestedTokenType *string `json:"requestedTokenType,omitempty"`
	// resource specifies the target resource for the exchanged token.
	// This typically identifies the target API server or service.
	Resource *string `json:"resource,omitempty"`
	// actorTokenSecretRef optionally references a secret containing an actor token.
	// This is used in delegation scenarios where the actor (controller) is acting
	// on behalf of the subject (user/service).
	ActorTokenSecretRef *SecretKeyReferenceApplyConfiguration `json:"actorTokenSecretRef,omitempty"`
	// actorTokenType specifies the type of the actor token.
	// Default: urn:ietf:params:oauth:token-type:access_token
	ActorTokenType *string `json:"actorTokenType,omitempty"`
}

// TokenExchangeConfigApplyConfiguration constructs a declarative configuration of the TokenExchangeConfig type for use with
// apply.
func TokenExchangeConfig() *TokenExchangeConfigApplyConfiguration {
	return &TokenExchangeConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithEnabled(value bool) *TokenExchangeConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithSubjectTokenSecretRef sets the SubjectTokenSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubjectTokenSecretRef field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithSubjectTokenSecretRef(value *SecretKeyReferenceApplyConfiguration) *TokenExchangeConfigApplyConfiguration {
	b.SubjectTokenSecretRef = value
	return b
}

// WithSubjectTokenType sets the SubjectTokenType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubjectTokenType field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithSubjectTokenType(value string) *TokenExchangeConfigApplyConfiguration {
	b.SubjectTokenType = &value
	return b
}

// WithRequestedTokenType sets the RequestedTokenType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequestedTokenType field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithRequestedTokenType(value string) *TokenExchangeConfigApplyConfiguration {
	b.RequestedTokenType = &value
	return b
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithResource(value string) *TokenExchangeConfigApplyConfiguration {
	b.Resource = &value
	return b
}

// WithActorTokenSecretRef sets the ActorTokenSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActorTokenSecretRef field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithActorTokenSecretRef(value *SecretKeyReferenceApplyConfiguration) *TokenExchangeConfigApplyConfiguration {
	b.ActorTokenSecretRef = value
	return b
}

// WithActorTokenType sets the ActorTokenType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActorTokenType field is set to the value of the last call.
func (b *TokenExchangeConfigApplyConfiguration) WithActorTokenType(value string) *TokenExchangeConfigApplyConfiguration {
	b.ActorTokenType = &value
	return b
}
