/*
Copyright 2026.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// WebhookSinkSpecApplyConfiguration represents a declarative configuration of the WebhookSinkSpec type for use
// with apply.
//
// WebhookSinkSpec configures an HTTP webhook audit sink.
type WebhookSinkSpecApplyConfiguration struct {
	// URL is the webhook endpoint.
	URL *string `json:"url,omitempty"`
	// Headers to include in requests.
	Headers map[string]string `json:"headers,omitempty"`
	// AuthSecretRef references a Secret for authentication.
	// The Secret can have keys "token" (Bearer) or "username"/"password" (Basic).
	AuthSecretRef *SecretKeySelectorApplyConfiguration `json:"authSecretRef,omitempty"`
	// TimeoutSeconds for HTTP requests.
	TimeoutSeconds *int `json:"timeoutSeconds,omitempty"`
	// TLS configuration.
	TLS *WebhookTLSSpecApplyConfiguration `json:"tls,omitempty"`
	// BatchSize for batched webhook calls.
	// If > 1, events are sent as JSON arrays.
	BatchSize *int `json:"batchSize,omitempty"`
	// BatchURL is an optional separate endpoint for batch requests.
	// If not specified, the main URL is used for both single and batch writes.
	// This allows using different endpoints for single vs batch operations.
	BatchURL *string `json:"batchUrl,omitempty"`
}

// WebhookSinkSpecApplyConfiguration constructs a declarative configuration of the WebhookSinkSpec type for use with
// apply.
func WebhookSinkSpec() *WebhookSinkSpecApplyConfiguration {
	return &WebhookSinkSpecApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *WebhookSinkSpecApplyConfiguration) WithURL(value string) *WebhookSinkSpecApplyConfiguration {
	b.URL = &value
	return b
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *WebhookSinkSpecApplyConfiguration) WithHeaders(entries map[string]string) *WebhookSinkSpecApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}

// WithAuthSecretRef sets the AuthSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthSecretRef field is set to the value of the last call.
func (b *WebhookSinkSpecApplyConfiguration) WithAuthSecretRef(value *SecretKeySelectorApplyConfiguration) *WebhookSinkSpecApplyConfiguration {
	b.AuthSecretRef = value
	return b
}

// WithTimeoutSeconds sets the TimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutSeconds field is set to the value of the last call.
func (b *WebhookSinkSpecApplyConfiguration) WithTimeoutSeconds(value int) *WebhookSinkSpecApplyConfiguration {
	b.TimeoutSeconds = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *WebhookSinkSpecApplyConfiguration) WithTLS(value *WebhookTLSSpecApplyConfiguration) *WebhookSinkSpecApplyConfiguration {
	b.TLS = value
	return b
}

// WithBatchSize sets the BatchSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BatchSize field is set to the value of the last call.
func (b *WebhookSinkSpecApplyConfiguration) WithBatchSize(value int) *WebhookSinkSpecApplyConfiguration {
	b.BatchSize = &value
	return b
}

// WithBatchURL sets the BatchURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BatchURL field is set to the value of the last call.
func (b *WebhookSinkSpecApplyConfiguration) WithBatchURL(value string) *WebhookSinkSpecApplyConfiguration {
	b.BatchURL = &value
	return b
}
