/*
SPDX-FileCopyrightText: 2025-2026 Deutsche Telekom AG

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// WebhookTLSSpecApplyConfiguration represents a declarative configuration of the WebhookTLSSpec type for use
// with apply.
//
// WebhookTLSSpec configures TLS for webhook connections.
type WebhookTLSSpecApplyConfiguration struct {
	// CASecretRef references a Secret containing the CA certificate.
	CASecretRef *SecretKeySelectorApplyConfiguration `json:"caSecretRef,omitempty"`
	// InsecureSkipVerify skips server certificate verification.
	InsecureSkipVerify *bool `json:"insecureSkipVerify,omitempty"`
}

// WebhookTLSSpecApplyConfiguration constructs a declarative configuration of the WebhookTLSSpec type for use with
// apply.
func WebhookTLSSpec() *WebhookTLSSpecApplyConfiguration {
	return &WebhookTLSSpecApplyConfiguration{}
}

// WithCASecretRef sets the CASecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CASecretRef field is set to the value of the last call.
func (b *WebhookTLSSpecApplyConfiguration) WithCASecretRef(value *SecretKeySelectorApplyConfiguration) *WebhookTLSSpecApplyConfiguration {
	b.CASecretRef = value
	return b
}

// WithInsecureSkipVerify sets the InsecureSkipVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureSkipVerify field is set to the value of the last call.
func (b *WebhookTLSSpecApplyConfiguration) WithInsecureSkipVerify(value bool) *WebhookTLSSpecApplyConfiguration {
	b.InsecureSkipVerify = &value
	return b
}
