# SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

# golangci-lint configuration for breakglass controller
# Aligned with t-caas team conventions (auth-operator reference config)
#
# Linter enablement strategy:
#   - Phase 1 (this config): linters that pass on the existing codebase
#   - Phase 2 (TODO): enable remaining linters after fixing existing violations
#   Disabled linters are documented below with issue counts for prioritization.

version: "2"

run:
  go: "1.25"
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly
  relative-path-mode: gomod

output:
  formats:
    text:
      path: stderr

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    # Code Quality
    - asasalint
    - asciicheck
    - copyloopvar
    - durationcheck
    - errcheck
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - loggercheck
    - nakedret
    - nosprintfhostport
    - predeclared
    - unconvert
    - unused

    # Static Analysis
    - staticcheck

    # Performance
    - bodyclose

    # Code Style
    - misspell
    - usestdlibvars
    - whitespace

  # TODO: Enable these linters incrementally after fixing existing violations.
  # Listed with approximate issue counts for prioritization (lowest first):
  #   - dupword          ~1 issue
  #   - importas         ~4 issues
  #   - dogsled          ~8 issues
  #   - noctx            ~11 issues   (most violations in tests)
  #   - errorlint        ~12 issues
  #   - nilnil           ~12 issues
  #   - nilerr           ~14 issues
  #   - nolintlint       ~15 issues
  #   - dupl             ~17 issues
  #   - gosec            ~18 issues   (many false positives for TLS config)
  #   - prealloc         ~18 issues
  #   - gocyclo          ~48 issues
  #   - lll              ~56 issues
  #   - errchkjson       ~62 issues
  #   - goconst          ~67 issues
  #   - intrange         ~96 issues
  #   - thelper          various      (test helpers missing t.Helper())
  #   - tparallel        various      (improper t.Parallel() usage)
  #   - unparam          various      (false positives in interface impls)
  #   - revive           ~381 issues  (noisy for exported comment checks)
  #   - godot            ~785 issues  (comment period enforcement)
  # When enabling, also uncomment the corresponding settings and exclusion
  # rules below.

  settings:
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - equalFold
      disabled-checks:
        - appendAssign
        - assignOp
        - captLocal
        - commentFormatting
        - deprecatedComment
        - dupBranchBody
        - elseif
        - exitAfterDefer
        - ifElseChain
        - regexpMust
        - sloppyLen
        - typeSwitchVar
        - underef
        - unlambda
        - unslice
    # Settings below are pre-configured for when the corresponding
    # linters are enabled (Phase 2).
    gocyclo:
      min-complexity: 20
    godot:
      scope: toplevel
      exclude:
        - "SPDX-"
        - "\\+kubebuilder"
    importas:
      no-unaliased: true
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/api/rbac/v1
          alias: rbacv1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
    lll:
      line-length: 180
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - disableStutteringCheck
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: empty-block
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: errorf
        - name: if-return
        - name: increment-decrement
        - name: indent-error-flow
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unexported-return
        - name: unreachable-code
        - name: unused-parameter
          disabled: true
        - name: var-naming
    gosec:
      excludes:
        - G104
        - G304
        - G402  # TLS InsecureSkipVerify (intentional in this project)
    staticcheck:
      checks:
        - "all"
        - "-QF1001"
        - "-QF1008"
        - "-ST1000"
        - "-ST1003"

  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go$
      - linters:
          - gocritic
        path: _test\.go$
      # Exclusion rules below are pre-configured for Phase 2 linters.
      - linters:
          - lll
        path: api/
      - linters:
          - dupl
        path: _test\.go$
      - linters:
          - gosec
        path: _test\.go$
      - linters:
          - revive
        path: _test\.go$
        text: "dot-imports"
      - linters:
          - godot
        path: _test\.go$
      - linters:
          - noctx
        path: _test\.go$
      - linters:
          - unparam
        path: _test\.go$
    paths:
      - "zz_generated.*\\.go$"
      - "_generated\\.go$"
      - ".*\\.pb\\.go$"
      - third_party$
      - builtin$
      - examples$
      - e2e$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - "zz_generated.*\\.go$"
      - "_generated\\.go$"
      - ".*\\.pb\\.go$"
