# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: CC0-1.0

# golangci-lint configuration for breakglass controller
# Aligned with t-caas team conventions (auth-operator reference config)
#
# All feasible linters are enabled and enforced.
# Remaining disabled linters are documented with issue counts and rationale.

version: "2"

run:
  go: "1.25"
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly
  relative-path-mode: gomod

output:
  formats:
    text:
      path: stderr

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    # Code Quality
    - asasalint
    - asciicheck
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - loggercheck
    - nakedret
    - nosprintfhostport
    - predeclared
    - tparallel
    - unconvert
    - unused

    # Static Analysis
    - staticcheck

    # Performance
    - bodyclose

    # Code Style
    - misspell
    - usestdlibvars
    - whitespace

  # Disabled linters — documented with issue counts and rationale:
  #
  # Fixable but high-volume (best addressed in dedicated PRs):
  #   - noctx          ~304 issues  (http.NewRequest → NewRequestWithContext; mostly in tests)
  #   - intrange        ~96 issues  (for i := 0; i < n; i++ → for i := range n)
  #   - errchkjson      ~62 issues  (unchecked json.Marshal/Unmarshal errors)
  #   - goconst         ~67 issues  (repeated string literals → constants)
  #   - thelper         ~158 issues (test helpers missing t.Helper())
  #   - prealloc        ~18 issues  (slice preallocation suggestions)
  #   - unparam         ~19 issues  (false positives in interface implementations)
  #
  # Too noisy / style-only (low value-to-noise ratio):
  #   - godot          ~1726 issues (comment period enforcement)
  #   - revive          ~747 issues (exported comment checks)
  #   - lll            ~1468 issues (line length limits)
  #   - dupl            ~104 issues (code duplication detection — many false positives in tests)
  #   - gocyclo          ~17 issues (cyclomatic complexity)
  #
  # Intentional patterns in this codebase:
  #   - nilnil          ~12 issues  (nil, nil returns are idiomatic for "not found, not an error")
  #   - nilerr          ~14 issues  (mostly e2e wait helpers returning false, nil to retry)
  #   - gosec          ~161 issues  (many false positives for TLS config in tests)
  #   - dogsled           ~8 issues (multi-return test helpers are standard Go test patterns)
  #   - nolintlint       ~15 issues (would require adding explanations to all nolint directives)

  settings:
    importas:
      no-unaliased: false
      alias:
        - pkg: "github.com/telekom/k8s-breakglass/api/v1alpha1"
          alias: breakglassv1alpha1
    gocritic:
      enabled-checks:
        - boolExprSimplify
        - equalFold
      disabled-checks:
        - appendAssign
        - assignOp
        - captLocal
        - commentFormatting
        - deprecatedComment
        - dupBranchBody
        - elseif
        - exitAfterDefer
        - ifElseChain
        - regexpMust
        - sloppyLen
        - typeSwitchVar
        - underef
        - unlambda
        - unslice
    staticcheck:
      checks:
        - "all"
        # Disable quick-fix suggestions that are style preferences
        - "-QF1001"   # Apply De Morgan's law
        - "-QF1002"   # Convert untagged switch to tagged switch
        - "-QF1003"   # Convert if/else-if chain to tagged switch
        - "-QF1008"   # Omit embedded fields from selector expression
        - "-QF1011"   # Omit redundant type from declaration
        # Disable style checks (too noisy for existing codebase)
        - "-ST1000"   # Package comment
        - "-ST1003"   # Underscores in names
        - "-ST1005"   # Error string capitalization
        - "-ST1016"   # Method receiver names
        - "-ST1019"   # Duplicate imports
        - "-ST1020"   # Function comment format
        - "-ST1021"   # Type comment format
        - "-ST1022"   # Variable comment format
        - "-ST1023"   # Redundant type in declaration
        # Disable SA checks
        - "-SA1012"   # nil context (often valid in tests)

  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        path: _test\.go$
      - linters:
          - gocritic
        path: _test\.go$
    paths:
      - "zz_generated.*\\.go$"
      - "_generated\\.go$"
      - ".*\\.pb\\.go$"

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - "zz_generated.*\\.go$"
      - "_generated\\.go$"
      - ".*\\.pb\\.go$"
