apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# DEPRECATED: Webhooks are now enabled by default in config/base.
# This target is maintained for backwards compatibility.
bases:
  - ../default
