apiVersion: breakglass.t-caas.telekom.com/v1alpha1
kind: BreakglassEscalation 
metadata:
  labels:
  name: kind-sample
spec:
  escalatedGroup: "cluster-admin"
  maxValidFor: "2h"
  approvalTimeout: "30m"
  allowed:
    clusters: ["example-cluster"]
    groups: 
      - oidc:platform-poweruser
      - oidc:platform-protected
      - platform-poweruser
      - platform-protected
  approvers:
    users: 
    - "approver-one@example.com"
    - "approver-two@example.com"

  # Example: require a request reason from the requester
  requestReason:
    mandatory: true
    description: "Please provide the related ticket ID"
---
apiVersion: breakglass.t-caas.telekom.com/v1alpha1
kind: BreakglassEscalation 
metadata:
  labels:
  name: kind-sample-2
spec:
  escalatedGroup: "platform-protected"
  maxValidFor: "2h"
  approvalTimeout: "30m"
  allowed:
    clusters: ["example-cluster"]
    groups: ["oidc:platform-protected"]
  approvers:
    users: 
    - "approver-one@example.com"
