//go:build !ignore_autogenerated

/*
Copyright 2024.

Here we can add license
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassEscalation) DeepCopyInto(out *BreakglassEscalation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassEscalation.
func (in *BreakglassEscalation) DeepCopy() *BreakglassEscalation {
	if in == nil {
		return nil
	}
	out := new(BreakglassEscalation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakglassEscalation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassEscalationAllowed) DeepCopyInto(out *BreakglassEscalationAllowed) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassEscalationAllowed.
func (in *BreakglassEscalationAllowed) DeepCopy() *BreakglassEscalationAllowed {
	if in == nil {
		return nil
	}
	out := new(BreakglassEscalationAllowed)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassEscalationApprovers) DeepCopyInto(out *BreakglassEscalationApprovers) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassEscalationApprovers.
func (in *BreakglassEscalationApprovers) DeepCopy() *BreakglassEscalationApprovers {
	if in == nil {
		return nil
	}
	out := new(BreakglassEscalationApprovers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassEscalationList) DeepCopyInto(out *BreakglassEscalationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BreakglassEscalation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassEscalationList.
func (in *BreakglassEscalationList) DeepCopy() *BreakglassEscalationList {
	if in == nil {
		return nil
	}
	out := new(BreakglassEscalationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakglassEscalationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassEscalationSpec) DeepCopyInto(out *BreakglassEscalationSpec) {
	*out = *in
	in.Allowed.DeepCopyInto(&out.Allowed)
	in.Approvers.DeepCopyInto(&out.Approvers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassEscalationSpec.
func (in *BreakglassEscalationSpec) DeepCopy() *BreakglassEscalationSpec {
	if in == nil {
		return nil
	}
	out := new(BreakglassEscalationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassEscalationStatus) DeepCopyInto(out *BreakglassEscalationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassEscalationStatus.
func (in *BreakglassEscalationStatus) DeepCopy() *BreakglassEscalationStatus {
	if in == nil {
		return nil
	}
	out := new(BreakglassEscalationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassSession) DeepCopyInto(out *BreakglassSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassSession.
func (in *BreakglassSession) DeepCopy() *BreakglassSession {
	if in == nil {
		return nil
	}
	out := new(BreakglassSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakglassSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassSessionList) DeepCopyInto(out *BreakglassSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BreakglassSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassSessionList.
func (in *BreakglassSessionList) DeepCopy() *BreakglassSessionList {
	if in == nil {
		return nil
	}
	out := new(BreakglassSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BreakglassSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassSessionSpec) DeepCopyInto(out *BreakglassSessionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassSessionSpec.
func (in *BreakglassSessionSpec) DeepCopy() *BreakglassSessionSpec {
	if in == nil {
		return nil
	}
	out := new(BreakglassSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BreakglassSessionStatus) DeepCopyInto(out *BreakglassSessionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ApprovedAt.DeepCopyInto(&out.ApprovedAt)
	in.ExpiredAfter.DeepCopyInto(&out.ExpiredAfter)
	in.RetainedUntil.DeepCopyInto(&out.RetainedUntil)
	in.IdleUntil.DeepCopyInto(&out.IdleUntil)
	in.LastUsed.DeepCopyInto(&out.LastUsed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BreakglassSessionStatus.
func (in *BreakglassSessionStatus) DeepCopy() *BreakglassSessionStatus {
	if in == nil {
		return nil
	}
	out := new(BreakglassSessionStatus)
	in.DeepCopyInto(out)
	return out
}
