# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: ORT Scan
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: 'recursive'

      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@086d928d24ef1653dc0777296b312fda5faaaf52 # v1.2.0
        with:
          ort-config-repository: 'https://github.com/telekom/ort-config.git'
          log-level: info